### ISSUE TITLE
REST API CustomerSavedSearch not working at all

### ISSUE THREAD

**Issue by slatem** [Shopify/shopify-api-ruby#1007]
# Issue summary

``ShopifyAPI::CustomerSavedSearch.all(session:session)``

returns 

``ShopifyAPI::Errors::HttpResponseError (Not found)``

Any call to CustomerSavedSearch returns a not found? We definitely have saved searches. Session looks good. Can make tons of other calls fine. I have customer_read and customer_write scope permissions. Any ideas?

- `shopify_api` version: 11.0.1
- Shopify API version used: 2022-04

**Comment by markbiegel** [comment]
Same issue using API version 2022-07
