### ISSUE TITLE
Logging type error

### ISSUE THREAD

**Issue by schonert** [Shopify/shopify-api-ruby#1013]
# Issue summary
I'm trying to change the global logger to `SemanticLogger::Logger` but facing a Sorbet type error.

## Expected behavior
I'd expect that ShopifyAPI would allow using any logger

## Actual behavior
Sorbet type check error

## Steps to reproduce the problem

1. Add `gem "rails_semantic_logger"` to gem file
1. `bundle install`
1. Set ShopifyAPI logger to Rails.logger in in Context.setup. ` ShopifyAPI::Context.setup( logger: Rails.logger )`
2. Start Rails `rails s`

## Logs
```
`cast': T.cast: Expected type Logger, got type SemanticLogger::Logger with hash 227568649015452756 (TypeError)
```

## Specifications

- `shopify_api` version: 11.1.0
- Shopify API version used (example: `2022-07`):

**Comment by multiplegeorges** [comment]
This error also occurs with GCP's Stackdriver gem, which replaces the Logger with a Google::Cloud::Logging::Logger.
