### ISSUE TITLE
How to return GraphQL::Client::Response instead of ShopifyAPI::Clients::HttpResponse (v10+)

### ISSUE THREAD

**Issue by netwire88** [Shopify/shopify-api-ruby#1020]
# Issue summary
After upgrading to 11.1.0 (or any version after v10),  `client.query` to returns `ShopifyAPI::Clients::HttpResponse`  instead of `GraphQL::Client::Response`. This breaks all code in our projects. How do we get `GraphQL::Client::Response` instead of `ShopifyAPI::Clients::HttpResponse`?

## Expected behavior

Receive data in `GraphQL::Client::Response` instead of `ShopifyAPI::Clients::HttpResponse`

## Actual behavior

`ShopifyAPI::Clients::HttpResponse` is returned. Result is a hash and no way to get objects such as `data` and `error`. Is there a way to:

1. Call `GraphQL::Client.query` instead of `ShopifyAPI`'s `query`, or
2. Pass the results `ShopifyAPI::Clients::HttpResponse` to `GraphQL::Client` to return `GraphQL::Client::Response`? 

## Steps to reproduce the problem

```
      ShopifyAPI::Auth::Session.temp(shop: account.shopify_domain, access_token: account.shopify_token) do |session|
        client = ShopifyAPI::Clients::Graphql::Admin.new(session: session)
        client.query(query: query, variables: variables)
      end
```

`client.query` returns `ShopifyAPI::Clients::HttpResponse`

## Specifications

- `shopify_api` version: 11.1.0
- Shopify API version used (example: `2020-07`): 2022-07

**Comment by skillmatic-co** [comment]
I'm having the same issue.
