### ISSUE TITLE
ActiveResource models all method does not support pagination? v10.x

### ISSUE THREAD

**Issue by jrubaloff** [Shopify/shopify-api-ruby#1024]
# Issue summary

The all methods on the model don't appear to support pagination which seems like it would render them useless. Is there a way to get to the next/prev page_info when using models and all method?

## Expected behavior

Pagination should be possible via next_page_info 

## Actual behavior

What actually happens?

## Steps to reproduce the problem

1. Have > 250 products in your store
1. products = ShopifyAPI::Product.all(session: session)
1. products.next_page_info doesn't work

## Logs

```
ShopifyAPI::Product.count(session: session)
=> #<ShopifyAPI::Clients::HttpResponse:0x00007fad715b9c78
 @body={"count"=>461},

products = ShopifyAPI::Product.all(session: session)
products.next_page_info
NoMethodError: undefined method `next_page_info'
```

## Specifications

- `shopify_api` version:
- Shopify API version used (example: `2022-04`):

**Comment by jrubaloff** [comment]
Aha!  You can access next_page? and next_page_info in ShopifyAPI::Product !

So make your call and then access on the product class:
```
ShopifyAPI::Product.all(session: session)
ShopifyAPI::Product.next_page?
ShopifyAPI::Product.next_page_info
```

**Comment by Trimakas** [comment]
@jrubaloff but then how do you actually get the next page? `ShopifyAPI::Product.fetch_next_page` doesn't work.
