### ISSUE TITLE
ShopifyAPI::Rest::Base#initialize has a from_hash argument but subclasses override it out

### ISSUE THREAD

**Issue by axlekb** [Shopify/shopify-api-ruby#1048]
# Issue summary

There's a seeminglyl useful `from_hash:` argument in `ShopifyAPI::Rest::Base#initialize`, but it's not usable because all subclasses override `#initialize`.

```ruby
# base.rb
def initialize(session: nil, from_hash: nil)
   # elided code

  from_hash&.each do |key, value|
    set_property(key, value)
  end
end
```

```ruby
# asset.rb
def initialize(session: ShopifyAPI::Context.active_session)
  super(session: session)
  # elided code
end
```

## Expected behavior

Initialize a `ShopifyAPI::Rest::*` object with `#new(from_hash: my_hash)`

## Actual behavior
```
ArgumentError: unknown keyword: :from_hash
```

## Specifications

- `shopify_api` version: `12.12.1`
- Shopify API version used: `2022-04`):

**Comment by raymondcoding** [comment]
It is a quite huge feature, I don't know why do not implement it.

**Comment by jamiemtdwyer** [comment]
Not stale.
