### ISSUE TITLE
500 Internal Server Error should raise ShopifyAPI::Errors::HttpResponseError

### ISSUE THREAD

**Issue by ristooi** [Shopify/shopify-api-ruby#1050]
# Issue summary

API calls like

> ShopifyAPI::DiscountCode.find(id: shopify_discount_code_id, price_rule_id: shopify_price_rule_id)

can naturally fail with `500 Internal Server Error`, but currently `shopify_api` is not raising an exception (ie. `ShopifyAPI::Errors::HttpResponseError`) in these cases.
Instead, I get a HTML response (see below), which then leads to a `JSON::ParserError`

## Expected behavior

`shopify_api` should raise `ShopifyAPI::Errors::HttpResponseError` with code 500

## Logs

JSON::ParserError

859: unexpected token at '

&lt;!--
  The source of truth for this generic error page is https://github.com/Shopify/error-pages.
  Please do not edit this file directly.
--&gt;
&lt;!DOCTYPE html&gt;
&lt;html lang="en"&gt;
  &lt;body class="status-error `status-code-500`"&gt;
    &lt;div class="page"&gt;
      &lt;div class="text-container text-container--main"&gt;
        &lt;div&gt;
          &lt;h1 data-i18n="content-title"&gt;There was a problem loading this website&lt;/h1&gt;
          &lt;p data-i18n="try-refreshing"&gt;Try refreshing the page.&lt;/p&gt;
          &lt;p data-i18n="try-again"&gt;If the site still doesn't load, please try again in a few minutes.&lt;/p&gt;
          &lt;a href="." class="action" data-i18n="refresh-page"&gt;Refresh Page&lt;/a&gt;
        &lt;/div&gt;
      &lt;/div&gt;
    &lt;/div&gt;
'

## Specifications

- `shopify_api` version: 12.2.1
- Shopify API version used: 2022-07

**Comment by kirillplatonov** [comment]
Not stale. The issue still exists.
