### ISSUE TITLE
Theme.all method is missing for ShopifyAPI 12.2.1

### ISSUE THREAD

**Issue by Kurbm** [Shopify/shopify-api-ruby#1060]
# Issue summary

Write a short description of the issue here ↓
It looks like in the shopify_api (12.2.1) the rest API call ShopifyAPI::Theme.all does not work. It says "undefined method `all' for ShopifyAPI::Theme:Class". How should we actually find the "live theme" to add assets or even check, if it is a OS2 or vintage theme?

## Expected behavior

What do you think should happen?
Get the actual "live" theme, if we make an API request like ShopifyAPI::Theme.all(params: {role: 'main'})

## Actual behavior

What actually happens?
I receive an error message, that the method is missing.

undefined method `all' for ShopifyAPI::Theme:Class

## Steps to reproduce the problem

1. Add the API call to a rails controller
2. Open an app, and see the error.

## Logs
If applicable, enable the logs as described in the README, and paste the relevant portion here.

## Specifications

- `shopify_api` version: 12.2.1
- Shopify API version used: 2022-10

**Comment by uurcank** [comment]
@Kurbm a lot of things changed and the documentation here is not up to date @andyw8 

https://github.com/Shopify/shopify-api-ruby/wiki/API-examples

**Comment by andyw8** [comment]
@Kurbm is it possible you have another class in your app called `Theme` which is clashing with this?

I verified it's working:

```
[4] pry(#<ProductsController>)> ShopifyAPI::VERSION
=> "12.2.1"
[5] pry(#<ProductsController>)> ShopifyAPI::Theme.all.size
=> 1
```

What does `ShopifyAPI.const_source_location(:Theme)` return for you?
