### ISSUE TITLE
ShopifyAPI::Asset.find('layout/theme.liquid') no longer works

### ISSUE THREAD

**Issue by asecondwill** [Shopify/shopify-api-ruby#1065]
Pre update to shopify_app 21 / shopify api12,  I could fetch a file from a theme like this

`ShopifyAPI::Asset.find('layout/theme.liquid') `

What is the new way to get Assets / theme files?  Is there any documentation for the new shopify_api gem?  there are lots and lots of changes and seemingly no docs at all? Hopefully I'm just not realising where?

**Comment by Kurbm** [comment]
@asecondwill what works for me is the following

ShopifyAPI::Asset.all(theme_id: ID ,asset: {key: "templates/index.json"})

As an example, where ID is the theme id, you would like to find the asset in.
