### ISSUE TITLE
`OrderRisk.all` REST Admin API always returns empty array

### ISSUE THREAD

**Issue by remy727** [Shopify/shopify-api-ruby#1068]
# Issue summary

Requesting order risks returns an empty array:
```
risks = ShopifyAPI::OrderRisk.all(order_id: order_id)
puts risks # [], even on orders showing high risk in Shopify admin
```
I tried this with REST.

## Expected behavior

Should get a response with the risks for that order.

## Actual behavior

An empty array is returned regardless of the risk level.

## Steps to reproduce the problem

Make the request: `ShopifyAPI::OrderRisk.all(order_id: order_id)`
See that it gives an empty array in response

## Specifications

- `shopify_api` version: 12.2.1
- Shopify API version: 2022-10

**Comment by remy727** [comment]
Until Shopify fixes it, we are using the following
```ruby
# Create a new order risk
session = ShopifyAPI::Context.active_session
client = ShopifyAPI::Clients::Rest::Admin.new(session: session)
response = client.post(path: "orders/#{order_id}/risks.json", body: { risk: payload })
new_order_risk = response.body['risk']
```

**Comment by kirillplatonov** [comment]
Still relevant

**Comment by nelsonwittwer** [comment]
Fixed with https://github.com/Shopify/shopify-api-ruby/pull/1153
