### ISSUE TITLE
What's up with Deprecations?

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify-api-ruby#1086]
Schema version 2022-10

Run this query using console: **getProductByHandle**

result is:

    Deprecated request to Shopify API at 2022-10/graphql.json, received reason: https://shopify.dev/api/usage/versioning#deprecation-practices
    {"data"=>{"productByHandle"=>nil}, "extensions"=>{"cost"=>{"requestedQueryCost"=>416, "actualQueryCost"=>1, "throttleStatus"=>{"maximumAvailable"=>1000.0, "currentlyAvailable"=>999, "restoreRate"=>50.0}}}}

OK. So I fired up the exact same query using Insomnia, performing the query getProductByHandle, using schema 2022-10 in the endpoint, and there are exactly zero indications that this call is deprecated. So at some point, how are we supposed to work with this, when one query informs us of impending disaster, yet another tells us nothing, yet they are equal. 

Also, why would this query even be deprecated? It is handy. Is there a better way to get at a product when all you know is its handle? What would that be?

**Comment by resistorsoftware** [comment]
Seeing this in my code, with no explanations as to what is deprecated. 

Deprecated request to Shopify API at 2022-10/graphql.json, received reason: https://shopify.dev/api/usage/versioning#deprecation-practices

**Comment by mariusa** [comment]
not stale

**Comment by ettoredn** [comment]
> It's so confusing. We've spent countless developer hours trying to figure it out. It requires lots of cross reference with shopify.dev + Graphiql Explorer. It's even crazy that some key endpoints are deprecated with no obvious alternative solution, such as [FulfillmentOrderLineItem.lineItem](https://shopify.dev/api/admin-graphql/2023-01/objects/FulfillmentOrderLineItem)

I'm using custom attributes for customized bundled products. In the cart, a variant (same SKU) with different properties/attributes are treated as **different line items**. FulfillmentOrderLineItem does not expose this info preventing me from composing the bundled product. Having a reference to the LineItem is a MUST, because the SKU is not sufficient.

Please either add line item attributes and drop FulfillmentOrderLineItem, or keep the latter.

**Comment by ghulamali16** [comment]
> > @jaspertandy were you able to resolve or find a workaround for this, I am encountering the same thing
> 
> Unfortunately not. I guess what's happening is the gem is making a call to fields/endpoints which will be deprecated so it's either fork it and fix it (which I might do!) or wait and hope they update the gem to stop calling them. It's a bit annoying that the error makes it sound like it's something you've done when it must be something in the gem itself, and it's very disappointing that Shopify can basically ignore the issue for 2 months then automatically close it. If they don't fix it, presumably it could start to affect production code.

Indeed. At first, I was confused too after bumping up the API version and handling all of the mentioned deprecations, turns out it was this **line_items** field I was getting in the response.

**Comment by mrpunkin** [comment]
> 

How did you end up determining that was the issue? I've placed my query into the GraphiQL Explorer and not seen any warnings, installed the app to run the query against my own store data, still no warnings, and called the Rest ShopifyAPI::DeprecatedApiCall endpoint which returns an empty array. I'm at a loss as to how to figure out what part of my GraphQL query is a problem.

**Comment by mrpunkin** [comment]
> > > @jaspertandy were you able to resolve or find a workaround for this, I am encountering the same thing
> > 
> > 
> > Unfortunately not. I guess what's happening is the gem is making a call to fields/endpoints which will be deprecated so it's either fork it and fix it (which I might do!) or wait and hope they update the gem to stop calling them. It's a bit annoying that the error makes it sound like it's something you've done when it must be something in the gem itself, and it's very disappointing that Shopify can basically ignore the issue for 2 months then automatically close it. If they don't fix it, presumably it could start to affect production code.
> 
> Indeed. At first, I was confused too after bumping up the API version and handling all of the mentioned deprecations, turns out it was this **line_items** field I was getting in the response.

How did you end up determining that was the issue? I've placed my query into the GraphiQL Explorer and not seen any warnings, installed the app to run the query against my own store data, still no warnings, and called the Rest ShopifyAPI::DeprecatedApiCall endpoint which returns an empty array. I'm at a loss as to how to figure out what part of my GraphQL query is a problem.

**Comment by mrpunkin** [comment]
> > > > @jaspertandy were you able to resolve or find a workaround for this, I am encountering the same thing
> > > 
> > > 
> > > Unfortunately not. I guess what's happening is the gem is making a call to fields/endpoints which will be deprecated so it's either fork it and fix it (which I might do!) or wait and hope they update the gem to stop calling them. It's a bit annoying that the error makes it sound like it's something you've done when it must be something in the gem itself, and it's very disappointing that Shopify can basically ignore the issue for 2 months then automatically close it. If they don't fix it, presumably it could start to affect production code.
> > 
> > 
> > Indeed. At first, I was confused too after bumping up the API version and handling all of the mentioned deprecations, turns out it was this **line_items** field I was getting in the response.
> 
> How did you end up determining that was the issue? I've placed my query into the GraphiQL explorer and not seen any warnings, installed the GraphiQL app to run the query against my own store data, still no warnings, and called the Rest ShopifyAPI::DeprecatedApiCall endpoint which returns an empty array. I'm at a loss as to how to figure out what part of my GraphQL query is a problem.

Ignore me. I figured it out after going row by row in the explorer and hovering to find the one deprecated call.

**Comment by resistorsoftware** [comment]
That is the only way we get it. Manual labor. I am not sure why the schema cannot scream the exact same thing when used outside the internal GraphiQL App. Why does that App exclusively get to tell us deprecations compared to our code and or other tooling? Is there something special being done on what IS there, and no tooling yet takes advantage of this? I wish Shopify would illuminate us with a brief explanation.
