### ISSUE TITLE
Incorrect OAuth documentation

### ISSUE THREAD

**Issue by HashNotAdam** [Shopify/shopify-api-ruby#1088]
## Overview/summary

I'm struggling to get OAuth working and the [documentation](https://github.com/Shopify/shopify-api-ruby/blob/v12.3.0/docs/usage/oauth.md) is incorrect.

In the section [Add a route to start OAuth](https://github.com/Shopify/shopify-api-ruby/blob/v10.0.0/docs/usage/oauth.md#add-a-route-to-start-oauth), the code includes:
```ruby
def login
  shop = request.headers["Shop"]

  auth_response = ShopifyAPI::Auth::Oauth.begin_auth(shop: domain, redirect_path: "/auth/callback")
  ...
```

`shop` is never used, and `domain` is never defined. Was it supposed to be that the request header supplied a domain?

**Comment by max-si-m** [comment]
simply replace `domain` with `shop`
