### ISSUE TITLE
GraphQL 2023-01 not supported by v12.3.0

### ISSUE THREAD

**Issue by netwire88** [Shopify/shopify-api-ruby#1094]
# Issue summary
We are getting this error: `Uncaught exception: Invalid version 2023-01, supported versions: ["unstable", "2022-10", "2022-07", "2022-04", "2022-01"]`

Looking into `ShopifyAPI.AdminVersions`, we see this

```
module ShopifyAPI
  module AdminVersions
    SUPPORTED_ADMIN_VERSIONS = T.let([
      "unstable",
      "2022-10",
      "2022-07",
      "2022-04",
      "2022-01",
    ], T::Array[String])

    LATEST_SUPPORTED_ADMIN_VERSION = T.let("2022-10", String)
  end

  SUPPORTED_ADMIN_VERSIONS = ShopifyAPI::AdminVersions::SUPPORTED_ADMIN_VERSIONS
  LATEST_SUPPORTED_ADMIN_VERSION = ShopifyAPI::AdminVersions::LATEST_SUPPORTED_ADMIN_VERSION
end
```

- `shopify_api` version: 12.3.0
- Ruby version: 3.1.2
- Operating system: MacOS

```
Uncaught exception: Invalid version 2023-01, supported versions: ["unstable", "2022-10", "2022-07", "2022-04", "2022-01"]
```

## Expected behavior

Support newly released versions

## Actual behavior

Does not support 2023-01

## Steps to reproduce the problem

Upgrade `shopify_app` to 21.3.1, which uses `shopify_api` 12.3

**Comment by resistorsoftware** [comment]
Just wow.
