### ISSUE TITLE
Product creation with metaobject_reference metafield raising INTERNAL_SERVER_ERROR in GraphQL API

### ISSUE THREAD

**Issue by mvpgomes** [Shopify/shopify-api-ruby#1117]
# Issue summary

When creating a Product with the new Metafield [types](https://shopify.dev/docs/apps/custom-data/metafields/types) `metaobject_reference` or `mixed_reference` (and their respective list types) `productCreate` mutation is returning an `INTERNAL_SERVER_ERROR_RESPONSE`.

- `shopify_api` version: 12.4
- Shopiy API version : `2023-01`
- Ruby version: 3.0
- Operating system: MacOS

## Expected behavior

- If metaobject exists Product with metafields should be successfully created.
- If metaobject don't exists Product with metafields is not created and error message with a status code 404 (or some internal representation) is sent back.

## Actual behavior

Mutation result is:

```ruby
{"errors"=>[{"message"=>"Internal error. Looks like something went wrong on our end.\nRequest ID: d5c2e144-66dc-42ba-99d2-738978fe9c83 (include this in support requests).", "extensions"=>{"code"=>"INTERNAL_SERVER_ERROR", "requestId"=>"d5c2e144-66dc-42ba-99d2-738978fe9c83"}}]}
```

## Steps to reproduce the problem

The bug should be reproducible by running the following mutation:

```ruby
query = <<~QUERY
  mutation createProductMetafields($input: ProductInput!) {
    productCreate(input: $input) {
      product {
        id
        metafields(first: 3) {
          edges {
            node {
              id
              namespace
              key
              value
            }
          }
        }
      }
      userErrors {
        message
        field
      }
    }
  }
QUERY

variables = {
  "input": {
    "metafields": [
       {
          "namespace"=>"my_field", 
          "key"=>"superduper_metaobject", 
          "type"=>"metaobject_reference", 
           "value"=>"gid://shopify/Metaobject/123"
        }
    ],
    "title": "Hiking Boots"
  }
}

client.query(query: query, variables: variables)
```

**Comment by thorupio** [comment]
Seeing the issue as well when creating a metafield of type `metaobject_reference` directly on an existing product using REST API

**Comment by thorupio** [comment]
on further examination, the `internal server error` is thrown if no metafield definition of type `metaobject_reference` exists for the namespace+key combo
