### ISSUE TITLE
Uninitialized Constant ShopifyAPI:: In GH Actions Test Environment Only

### ISSUE THREAD

**Issue by cisenor1** [Shopify/shopify-api-ruby#1130]
# Issue summary

When I run my project locally (OSX 2021 MacBook), all my Rspec tests pass as expected. When I then push to GitHub, we have checks in place that run Rspec. For whatever reason, in CI/GH only, the project fails with "Uninitialized Constant ShopifyAPI" for every test that references it. 

- `shopify_api` version: 12.4.0
- Ruby version: 2.7.7
- Operating system: OSX Locally, Ubuntu 22 LTS on GH Actions server

## Expected behavior

The project should run tests as expected (and hopefully pass)

## Actual behavior

No luck. Fails with "Uninitialized Constant ShopifyAPI"

**Comment by key88sf** [comment]
@cisenor1 What was the solution here? Getting the same thing in my test environment.
