### ISSUE TITLE
Cookies Fallback Doesn't Work in Shopify App under Embedded Mode

### ISSUE THREAD

**Issue by berniechiu** [Shopify/shopify-api-ruby#1158]
# Issue summary

- `shopify_api` version: 12.4.0
- Ruby version: 3.0.3
- Operating system: MacOS Ventura 13.3.1

Hi, in the `shopify_app` gem there's a method called `load_current_session(...)`, which contructs the session like this

https://github.com/Shopify/shopify_app/blob/dd47eb85472cde7db5869c14994896deacaad02c/lib/shopify_app/controller_concerns/login_protection.rb#L49-L64

And there's a fallback between within `embedded?` using cookie value

https://github.com/Shopify/shopify-api-ruby/blob/9e3008dac960eda0b8028d815780eff715b0bbd0/lib/shopify_api/utils/session_utils.rb#L20-L43

However, between embedded mode vs non-embedded mode, the cookie value does not correctly apply the **Shopify domain** when under the key `shopify_app_session`

Embedded
<img width="540" alt="Screen Shot 2023-05-17 at 3 34 21 PM" src="https://github.com/Shopify/shopify-api-ruby/assets/2749593/4cd761d1-9457-4ee4-95cc-fdaccf326b3f">

Non-Embedded
<img width="561" alt="Screen Shot 2023-05-17 at 3 34 12 PM" src="https://github.com/Shopify/shopify-api-ruby/assets/2749593/06fc2e72-cd0e-4925-afed-0c0fa7de17a1">

Thus, the fallback will never succeed under embedded app for the cookie fallback

The issue could be that we don't build anything in the returned cookie anymore which causes the discrepancy behaviour here

https://github.com/Shopify/shopify-api-ruby/blob/9e3008dac960eda0b8028d815780eff715b0bbd0/lib/shopify_api/auth/oauth.rb#L84-L94

## Expected behavior

`cookies.permanent["shopify_app_session"]` should be the same which assigns correctly with Shopify domain

## Actual behavior

`cookies.permanent["shopify_app_session"]` is not assigned correctly with a random key

## Steps to reproduce the problem

1.

**Comment by itsmeurbi** [comment]
We're dealing with the same issue ^
