### ISSUE TITLE
13.0.0+ session_storage documentation wrong

### ISSUE THREAD

**Issue by matthewlein** [Shopify/shopify-api-ruby#1163]
## Overview/summary

I was looking forward to the next release to fix some important but, but I see its been done in a breaking release with some significant session storage changes...

In trying to update, I now get errors about session storage, but the documentation is all unchanged. 

1. The current documentation for session_storage appears to be outdated (I think this option no longer exists?)
https://github.com/Shopify/shopify-api-ruby/blob/fca16f181f528216a98edf8a4db8c572e2d82e7d/README.md?plain=1#L55

3. The Setup a Session Store section appears to be outdated and references things that no longer exist.

4. The linked session storage also appears to be outdated. https://github.com/Shopify/shopify-api-ruby/blob/fca16f181f528216a98edf8a4db8c572e2d82e7d/docs/usage/session_storage.md

5. if `shopify_app` is now required to do sessions, can you document how that works completely? Ideally also including people that just run this as a CLI or script kind of thing as mentioned in https://github.com/Shopify/shopify-api-ruby/issues/1084

is `shopify_app` now a hard dependency? If so, I'd like to see more documentation on that. 

Personally, I'm using the shopify gem in a private app to run code just for our store. I don't need anything that shopify_app provides, so for me, this is not a good change. I was perfectly fine using the filesystem based session storage, I'd rather not make a new table and introduce all the session data there for no reason. Is there a way to do that?

**Comment by matthewlein** [comment]
@nelsonwittwer I've seen you on all the session storage PRs, are you the best one to document this?

**Comment by nelsonwittwer** [comment]
I'll update the documentation, thanks for bringing this up!

There is no dependency on `shopify_app`, no. I'll clarify this in the docs when I update them here. The responsibility of session storage was something we wanted removed from scope of all of our api libraries as that responsibility typically is fulfilled by the web framework middleware, in this case Rails. The API libraries are meant to facilitate creating a session and making requests with those sessions to our APIs. 

Totally see how this impacts your use case with only wanting file session storage. If you are interested in preserving this functionality, we'd be happy to promote a new gem that used the code that was dropped with the latest version if you or anyone else in the community wanted to take point on that :)
