### ISSUE TITLE
GraphQL Support?

### ISSUE THREAD

**Issue by jagthedrummer** [Shopify/shopify-api-ruby#1168]
# Issue summary

What happened to GraphQL support in version 10? There used to be a rake task for downloading the latest schema, but that seems to have disappeared.

- `shopify_api` version: 10.x
- Ruby version: any
- Operating system: any

## Expected behavior

This stuff should be documented.

## Actual behavior

This stuff is not documented.

## Steps to reproduce the problem

1. Try to upgrade an existing app from v9 to v10.
1. You're gonna have a bad time.

**Comment by jagthedrummer** [comment]
not stale

**Comment by zzooeeyy** [comment]
Hi @jagthedrummer,

We have removed our dependency to GraphQL client, so you no longer have to download schemas to download the schema to use GraphQL with our Admin API. The [GraphQL references on shopify.dev](https://shopify.dev/docs/api/admin-graphql) would be your best resource on our admin GraphQL schema, with examples and documentation.

We recently added more detail to our documentation, and here are some quick links to our references:
- [Breaking change notice for version 10](https://github.com/Shopify/shopify-api-ruby/blob/main/BREAKING_CHANGES_FOR_V10.md)
  -  This includes what's new, a more comprehensive upgrade guide and usage documentation 
- [Making GraphQL API calls](https://github.com/Shopify/shopify-api-ruby/blob/main/docs/usage/graphql.md)
  - Making API calls with GraphQL Admin Client
- [Custom Apps](https://github.com/Shopify/shopify-api-ruby/blob/main/docs/usage/custom_apps.md) 
  - Small guide on how to construct a session object to be used for making authenticated API calls for custom apps if you already have an API key. 
   
You can see a list of [all documentation we recently modified](https://github.com/Shopify/shopify-api-ruby/issues/1103#issuecomment-1736343971)

**Comment by zzooeeyy** [comment]
Closing this ticket now that there are improvements made to the docs. Feel free to open other tickets for specific issues you encounter and we'll try our best to answer your questions. Thanks everyone!
