### ISSUE TITLE
ShopifyAPI::Rest::Base responds_to everything

### ISSUE THREAD

**Issue by fmichaut-diff** [Shopify/shopify-api-ruby#1171]
Doing `ShopifyAPI::Order.new(session: session).abcdef` does not raise an error. It simply returns `nil`.

I believe this is the culprint : 
https://github.com/Shopify/shopify-api-ruby/blob/94591589ff57d8dcb3f37a97f70620766bb92ad6/lib/shopify_api/rest/base.rb#L280

Should be `match.nil? ? super : true`

**Comment by fmichaut-diff** [comment]
I would like to add that this behavior is breaking lots of things, one of them is the `present?` method from Rails : 
```
shopify_order = nil
if ....
  shopify_order = ShopifyAPI::Order.new
end
shopify_order.present?
```
This will return `false` if the order is still `nil`, but will error out if the order is an instance of `ShopifyAPI::Order` : 
```
~/.rvm/gems/ruby-3.2.0/gems/shopify_api-10.1.0/lib/shopify_api/rest/base.rb:369:in `instance_variable_get': `@empty?' is not allowed as an instance variable name (NameError)

        instance_variable_get("@#{clean_key}")
        ^^^^^^^^^^^^^^^^^^^^^
```

**Comment by nelsonwittwer** [comment]
This is an unfortunate implementation of how the REST resources are generated. We have a plan to extract these resources into their own gem and open source the logic that generates them. When we do so, we can explore alternative solutions there. As is now, this isn't something we can address. The goal is to have more flexibility/customization with that extraction and I hope to explore this then.
