### ISSUE TITLE
Readme Documentation needs to be updated

### ISSUE THREAD

**Issue by Trehana** [Shopify/shopify-api-ruby#1198]
# Issue summary

If not using the [shopify_app](https://github.com/Shopify/shopify_app) gem, your app needs to provide an implementation of ShopifyAPI::Auth::SessionStorage for production. Read more about this [in our documentation](https://github.com/Shopify/shopify-api-ruby/blob/main/docs/usage/session_storage.md).

## Expected behavior

Either this step should removed or updated with the correct link

**Comment by zzooeeyy** [comment]
Fixed in
- https://github.com/Shopify/shopify-api-ruby/pull/1201
