### ISSUE TITLE
GraphQL Client inadequate since v10 upgrade 

### ISSUE THREAD

**Issue by zzooeeyy** [Shopify/shopify-api-ruby#1210]
# Overview
[graphql-client](https://github.com/github/graphql-client) gem dependency was removed in the [shopify-api-ruby v10 upgrade](https://github.com/Shopify/shopify-api-ruby#breaking-change-notice-for-version-1000).

Instead of being able to access methods from objects to retrieve GraphQL response data, we return an HTTPResponse object instead, which means devs would have to retrieve data via hashes...

Before:
```
client = ShopifyAPI::GraphQL.client

SHOP_NAME_QUERY = client.parse <<-'GRAPHQL'
  {
    shop {
      name
    }
  }
GRAPHQL

result = client.query(SHOP_NAME_QUERY)
shop_name = result.data.shop.name
```

After:
```
client = ShopifyAPI::Clients::Graphql::Admin.new(session: session)

# make the GraphQL query string
query =<<~QUERY
  {
    shop {
      name
    }
  }
QUERY

response = client.query(query: query)
shop_name = response.body["data"]["shop"]["name"]
```

As you can see, this make migration and usage of the response data very difficult..
`shop_name = result.data.shop.name` vs 
`shop_name = response.body["data"]["shop"]["name"]`
It's especially challenging if there are even more layers like

`result.data.webhookSubscriptions.edges[0].node.id` vs
`response.body["data"]["webhookSubscriptions"]["edges"][0]["node"]["id"]`

## Expected behavior
We should add support to allow method access for GraphQL data instead of hash access to avoid this undesirable v10 migration side effect for existing apps, and improve new developer's GraphQL experience when building new apps.

## Example Complaint
> Agreed, it's virtually impossible to upgrade to v10 or later since the library no longer supports [graphql-client](https://github.com/github/graphql-client), with no options to support it. This renders all existing GraphQL code not compatible. I'm not sure how Shopify engineering team can get rid (forget even deprecating) an existing core library and think it's ok.

[Link to Comment](https://github.com/Shopify/shopify-api-ruby/issues/1032#issuecomment-1279864265)

**Comment by Javierchik** [comment]
What if you use OpenStruct? It should do the trick.
