### ISSUE TITLE
No passed or active session (ShopifyAPI::Errors::NoActiveSessionError)

### ISSUE THREAD

**Issue by sajjadmurtaza** [Shopify/shopify-api-ruby#1224]
# Issue summary

I setup new project and added `gem 'shopify_api', '~> 13.1.0'`

Here is my `initializers/shopify_api.rb`

```
ShopifyAPI::Context.setup(
  api_key: ENV['SHOPIFY_API_KEY'],
  api_secret_key: ENV['SHOPIFY_SECRET_KEY'],
  host: ENV['SHOPIFY_SHOP_NAME'],
  scope: 'read_products,write_products,read_orders,write_orders',
  is_embedded: false,
  api_version: ENV['SHOPIFY_API_VERSION'],
  is_private: true
)
```

When i run on rails console(to make sure if i can call shopify object):

> ShopifyAPI::Product.all
/Users/username/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/shopify_api-13.1.0/lib/shopify_api/clients/http_client.rb:14:in `initialize': No passed or active session (ShopifyAPI::Errors::NoActiveSessionError)

No passed or active session (ShopifyAPI::Errors::NoActiveSessionError)

- `shopify_api` version:
- Ruby version: 13.1.0
- Operating system: mac

```
lib/shopify_api/clients/http_client.rb:14:in `initialize': No passed or active session (ShopifyAPI::Errors::NoActiveSessionError)```

## Expected behavior

Should connect and return the products 

## Actual behavior

returning error:  NoActiveSessionError

**Comment by ziaulrehman40** [comment]
What was the issue?
