### ISSUE TITLE
ShopifyAPI::Rest::Base#initialize has a from_hash argument but subclasses override it out

### ISSUE THREAD

**Issue by eni9889** [Shopify/shopify-api-ruby#1233]
# Issue summary
There's a seeminglyl useful `from_hash:` argument in `ShopifyAPI::Rest::Base#initialize`, but it's not usable because all subclasses override `#initialize`.

```ruby
# base.rb
def initialize(session: nil, from_hash: nil)
   # elided code

  from_hash&.each do |key, value|
    set_property(key, value)
  end
end
```

```ruby
# asset.rb
def initialize(session: ShopifyAPI::Context.active_session)
  super(session: session)
  # elided code
end
```

## Expected behavior
Initialize a `ShopifyAPI::Rest::*` object with `#new(from_hash: my_hash)`

## Actual behavior
```
ArgumentError: unknown keyword: :from_hash
```

## Specifications
* `shopify_api` version: `13.2.0`
* Shopify API version used: `2023-10`):

**Comment by waruboy** [comment]
Up! this function is still featured quite prominently in the latest version of doc:
https://github.com/Shopify/shopify-api-ruby/blob/6c2a45f8377ac46217f9dd24068667ccd2a4ee5c/docs/usage/rest.md?plain=1#L51
