### ISSUE TITLE
Include X-Shopify-Webhook-Id to webhook handlers

### ISSUE THREAD

**Issue by forsbergplustwo** [Shopify/shopify-api-ruby#1247]
## Overview/summary

As per [Shopify's best practices for handling Webhooks](https://github.com/Shopify/shopify-api-ruby/blob/459b04e4cc58942866c0b53a5ece0bac73d90167/lib/shopify_api/webhooks/request.rb#L1-L56), we should be checking the webhook id for duplicates when processing. For example, we could use it to ensure only a single background job is enqueued for a specific webhook id at any one time.

Unfortunately the ShopifyAPI does not include the `X-Shopify-Webhook-Id` to our webhook handlers, and so we have no way of following these best practices when using the gem.

https://github.com/Shopify/shopify-api-ruby/blob/459b04e4cc58942866c0b53a5ece0bac73d90167/lib/shopify_api/webhooks/request.rb#L1-L56

Would a PR be accepted for this?

**Comment by resistorsoftware** [comment]
You'd think they would LOVE PR's that fix/improved this gem. That is the entire point of this exercise! Duped Webhooks! A thing since inception. We love having to manually detect dupes with code. It is our raison d'etre.

**Comment by forsbergplustwo** [comment]
Yaaay, thank you @lizkenyon 🙌

**Comment by lizkenyon** [comment]
@forsbergplustwo Sorry for the slow reply on this. 
This should go out in the next release. Please let us know if you run into any issues with it! 😄

**Comment by resistorsoftware** [comment]
I for one would love it if only Shopify would scrap this entire webhook architecture that makes us install 1, 4, 14 webhooks per store, when it would be so much nicer if we just register our 1, 4 or 14 webhooks with Shopify, and it then uses those per store we install our Apps too. If I have 2000 stores with my App and 14 webhooks registered for each one, and I change my webhook endpoint, I now have the lovely options of:
- aliasing OLD to NEW in my App ===> Crunky
- deleting all OLD and replacing with new (2000 stores times 14 webhooks)  ===> Crunky
- informing the registery of NEW endpoints for 14 webhooks once   ====> Hot to Trot

Ya... I know. Off topic. Crazy... but honestly, after 1 dozen plus years with this established old routine, that only now is getting even minor attention... can we not just blow it up and replace it something slick rick and groovy?

**Comment by forsbergplustwo** [comment]
@resistorsoftware - Please don’t hijack this thread for your off-topic rants.

**Comment by lizkenyon** [comment]
> I for one would love it if only Shopify would scrap this entire webhook architecture that makes us install 1, 4, 14 webhooks per store, when it would be so much nicer if we just register our 1, 4 or 14 webhooks with Shopify, and it then uses those per store we install our Apps too. If I have 2000 stores with my App and 14 webhooks registered for each one, and I change my webhook endpoint, I now have the lovely options of:
> 
> * aliasing OLD to NEW in my App ===> Crunky
> * deleting all OLD and replacing with new (2000 stores times 14 webhooks)  ===> Crunky
> * informing the registery of NEW endpoints for 14 webhooks once   ====> Hot to Trot
> 
> Ya... I know. Off topic. Crazy... but honestly, after 1 dozen plus years with this established old routine, that only now is getting even minor attention... can we not just blow it up and replace it something slick rick and groovy?

Hi @resistorsoftware 

We think you have brought up some good points here. The webhooks team is currently working on improvements in this space. These things take time, but please keep an eye of for improvements and releases in this areas!
