### ISSUE TITLE
ShopifyAPI::Errors::InvalidWebhookError: Missing one or more of the required HTTP headers to process webhooks: ["x-shopify-shop-domain"] for customers_redact, shop_redact webhooks

### ISSUE THREAD

**Issue by netwire88** [Shopify/shopify-api-ruby#1261]
# Issue summary

Since Jan 8, 2024 (assuming related to 2024-01 release), we are seeing `Missing one or more of the required HTTP headers to process webhooks: ["x-shopify-shop-domain"]` to process webhooks errors for `/customers_redact`, `/shop_redact` webhooks

- `shopify_api` version: 13.3.1
- Ruby version: ruby 3.2.2
- Operating system: All

See below for info, IP's redacted

```
X-Shopify-Test : false
X-Request-Id : 442d1310-af02-472d-b861-b82569c4e794
Content-Length : 164
Version : HTTP/1.1
X-Request-Start : 1704816527008
User-Agent : Shopify-Captain-Hook
X-Shopify-Topic : customers/redact
Cf-Ipcountry : NL
X-Shopify-Webhook-Id : 948128c5-b69e-4143-a514-72768dba8885
Cf-Visitor : {"scheme":"https"}
Accept-Encoding : gzip
X-Forwarded-Port : 443
Total-Route-Time : 0
Connection : close
Cf-Ray : 842df0dc3e821c89-AMS
X-Shopify-Triggered-At : 2024-01-09T16:08:46.395212977Z
Via : 1.1 vegur
Accept : */*
X-Forwarded-Proto : https
Connect-Time : 0
Content-Type : application/json
```

## Expected behavior

No error

## Actual behavior

ShopifyAPI::Errors::InvalidWebhookError raised with  `Missing one or more of the required HTTP headers to process webhooks: ["x-shopify-shop-domain"]` 

## Steps to reproduce the problem

**Comment by lizkenyon** [comment]
Hi there 👋 

I believe this issue has been resolved! Can you confirm you are no longer seeing these errors?

**Comment by netwire88** [comment]
Thanks @lizkenyon We haven't seen this since Jan 9.
