### ISSUE TITLE
Resources not loading when using session based auth

### ISSUE THREAD

**Issue by agbaber** [Shopify/shopify-api-ruby#1263]
# Issue summary

When using session-based auth, admin API resources are not being autoloaded correctly. Note that this is the same issue as [this one](https://github.com/Shopify/shopify-api-ruby/issues/1253), which was auto-closed.

- `shopify_api` version: 13.3.1
- Ruby version: 3.2.2
- Operating system: Mac OS Ventura 13.6.3

```
require 'shopify_api'
=> true

session = ShopifyAPI::Auth::Session.new(
  shop: "myshopname.myshopify.com"
  access_token: "token_for_my_custom_app_found_in_admin"
)
=> 
#<ShopifyAPI::Auth::Session:0x000000012611da10
...

ShopifyAPI::Product.all(session: session)

(irb):7:in `<main>': uninitialized constant ShopifyAPI::Product (NameError)
Did you mean?  Proc
	from /Users/andrewb/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'
	from /Users/andrewb/.rbenv/versions/3.2.2/bin/irb:25:in `load'
	from /Users/andrewb/.rbenv/versions/3.2.2/bin/irb:25:in `<main>'
```

## Expected behavior

The latest-versioned `Resources` should be autoloaded when an explicit version is not specified.

## Actual behavior

The gem does not load the `Resources` and returns an `uninitialized constant ` error.

## Steps to reproduce the problem

1. require the gem (`require 'shopify_api'`)
2. make a session with `ShopifyAPI::Auth::Session.new`
3. attempt to use that session to access a resource (`ShopifyAPI::Product.all(session: session)`)

**Comment by sshaw** [comment]
Just had the same problem myself with 13.3.1 under Ruby 3.1 and 2.7. So many docs, but not a single way showing you how to require. Upon further investigation, it looks like this is intentional as they're using Zeitwerk! 

My my my what in tarnation have they done to this library! REST API call now require native library compilation and installing sorbet-runtime 😱🤯👎

**Comment by sshaw** [comment]
@agbaber here is what you must do, in some form. This case assumes you're calling from an app but hopefully this will get you somewhere: 


```rb
ShopifyAPI::Context.setup(
  :api_key => a,
  :api_secret_key => b
  :api_version => "2023-07",
  :is_private => false,
  :scope => "your scopes",
  :is_embedded => false
)

ShopifyAPI::Context.activate_session(
  ShopifyAPI::Auth::Session.new(
    :shop => shopify_domain,
    :access_token => shopify_token,
  )
)

ShopifyAPI::Product.find(id: id)
```

zOMG

**Comment by lizkenyon** [comment]
Hi folks 👋 

Thank you for the feedback, I appreciate it, I am going to bring this up with the team. I definitely understand the confusion.
I am glad to hear that you have been able to work around this, and get this working.

**Comment by sle-c** [comment]
hey folks, this results from a breaking change in v10 of this gem https://github.com/Shopify/shopify-api-ruby/blob/main/BREAKING_CHANGES_FOR_V10.md

We're updating the doc to reflect that.
