### ISSUE TITLE
api_object.present? does not work

### ISSUE THREAD

**Issue by jasonbuehler** [Shopify/shopify-api-ruby#1283]
An unexpected error is raised when calling api_object.present?, `NameError ('@empty?' is not allowed as an instance variable name)`

- `shopify_api` version: 13.4.0
- Ruby version: 2.7.7
- Operating system: Mac OS 12.6 Monterey

## Expected behavior

If the object is not nil it should return true, otherwise it should return false

## Actual behavior

An non-relevant error was raised `NameError ('@empty?' is not allowed as an instance variable name)`

## Steps to reproduce the problem

1. Instantiate an api object `api_product = shop.with_shopify_session { ShopifyAPI::Product.new }`
2. Invoke .present? on the object ` api_product.present? `

**Comment by sle-c** [comment]
Hi @jasonbuehler , 

Thank you for opening this issue, this is related to the one you opened here 
https://github.com/Shopify/shopify-api-ruby/issues/1273

I'll close this issue for because it's a duplicate.

Si Le
