### ISSUE TITLE
Update variant through product destroys and creates variant instead

### ISSUE THREAD

**Issue by EmmaB** [Shopify/shopify-api-ruby#337]
When I update `variants` through a `product`, the variant is destroyed then a new one created. This breaks integrations that use the `variant_id`. 
```
      remote_product = ShopifyAPI::Product.where(handle: product.id).first
      if remote_product.update_attributes(product.to_h)
      ...
```
`product.to_h` is

```
{:title=>"Why xxx", :handle=>"84087", :product_type=>"HTML", :published_scope=>"global", :body_html=>"<p>Amended long text.</p>", :variants=>[{:barcode=>"9781xxx3634", :title=>"Why xxx", :price=>"55.0", :requires_shipping=>false, :taxable=>true}], :metafields=>[{xxx}], :tags=>"xxx", :images=>[]}
```
I can get around it via 

```
        if remote_product.update_attributes(product.to_h.except(:variants))
```
but then I can't update the price. I suppose I would have to send the `variant_id`, would I, or update `Variant` directly, but that's yet more API calls. Thoughts welcome.

**Comment by Eralph** [comment]
would be better if we can have a single call to update/create variants(with images) with Product.

**Comment by wakproductions** [comment]
@EmmaB Have you tried including the variant ID in the variants hash?

It also works for me if rather than using `update_attributes` just create a new `ShopifyAPI::Product`, set the `id` fields appropriately, and then call `#save!`

**Comment by EmmaB** [comment]
And this weird pattern of destroying data on an update has bitten me again, a year later. Shopify are unable to retrieve image data from S3 within 2 seconds (god knows why). When their call fails, since their "update" is actually a "destroy", I'm left with no image.
