### ISSUE TITLE
Product image position (main image) on image creation

### ISSUE THREAD

**Issue by Bran99** [Shopify/shopify-api-ruby#380]
I have successfully implemented image creation, attaching the product id.  However, I'm attempting to set the image as the main image (`position: 1`).  While I'm not getting any errors, the image position doesn't seem to be getting set.

My class has the following method:
```
class ProductVideo < ActiveRecord::Base
...
  private
  def create_poster_in_shopify
    product = self.product
    position = get_position
    shopify_product = ShopifyAPI::Product.find(product.shopify_id)
    file = File.read("#{Rails.root.join('public').to_s}#{self.video.url(:thumb)}")
    image = ShopifyAPI::Image.new
    image.attach_image(file)
    image.prefix_options={product_id: shopify_product.id, position: 1}
    image.save
    product.set_shopify_image_id(shopify_product, image.id)
  end
...
end
```

Is my syntax incorrect, or is this just not implemented?

**Comment by tin-tnguyen** [comment]
Could you capture the error?

**Comment by aalbina** [comment]
Have the same issue.

I'm creating the product. It creates without any error and I even can see my image in admin panel as a capture of the product. But it doesn't add to Media images, so I can't see image at Catalog page.

What I've already tried:
1. Add base64 of the image to attach attribute of ShopifyAPI::Image.new
2. Add url to src attribute
3. Add Base64.decode result via attach_image
4. Create temporary file and send it (via attach_image)
5. Send product_id, variant_id, position

None of this worked

**Comment by roseliux** [comment]
what I did was 
```
  shopify_product = ShopifyAPI::Product.find("THE_ID")
  image = ShopifyAPI::Image.new
  image.attach_image(file)
  image.prefix_options= { product_id: product.id, position: 1 }
  shopify_product.images = [image]
  shopify_product.save

```

and when I inspect the products again they have the position 1 set
