### ISSUE TITLE
errors.full_messages does not serialize correctly

### ISSUE THREAD

**Issue by gillisd** [Shopify/shopify-api-ruby#389]
When I print `errors.full_messages` on an instance of `ShopifyApi::Checkout`, I get an unusable response that looks like the following: 
```
Line items ["1", {"quantity"=>[{"code"=>"greater_than_or_equal_to", "message"=>"must be greater than or equal to 1", "options"=>{"count"=>1}}]}]
Shipping address ["province_code", [{"code"=>"invalid_region_in_country", "message"=>"is not a valid region in Egypt", "options"=>{"country"=>"Egypt"}}]]
```

I'd imagine that it supposed to output something like, as this is similar to what ActiveRecord would output if there is a validation error:

```
Line item #2 quantity must be greater than or equal to 1
Shipping address province code is not a valid region in Egypt
```

**Comment by adfaris** [comment]
I would need an invalid `checkouts` fixture error in order to fix this issue. 

https://github.com/Shopify/shopify_api/blob/3228e5d3a5fa5d2825eec0d5ff17a634cea7a093/test/fixtures/checkouts.json

cc @tanema
