### ISSUE TITLE
Could Address models like BillingAddress ShippingAddress inherit from Address ?

### ISSUE THREAD

**Issue by nicolasleger** [Shopify/shopify-api-ruby#399]
In `shopify_api/lib/shopify_api/resources/`

**Comment by jamiemtdwyer** [comment]
I think I would be hesitant about doing this, since they aren't really modelled in this way in the actual API. Do you have a specific use case for this in mind?

**Comment by nicolasleger** [comment]
Those models seems to be modelled as same as Address for example `billing_address` / `shipping_address ` in https://help.shopify.com/api/reference/order or `addresses` / `default_address` (I have seen a `ShopifyAPI::Customer::DefaultAddress`) in https://help.shopify.com/api/reference/customer and also https://help.shopify.com/api/reference/customeraddress got the same fields

It would be easier then to implement a generic processing of whatever address object we have on our side.
