### ISSUE TITLE
Price Rules count not working

### ISSUE THREAD

**Issue by smandegar** [Shopify/shopify-api-ruby#401]
It looks like the `PriceRule` class supports `Countable` but the Shopify API does not have a count endpoint available for that. Any idea on if this is an endpoint Shopify is planning on releasing?

```
> account.with_shopify_session { ShopifyAPI::PriceRule.count }

HTTP GET (73.90ms)   https://[shop_name].myshopify.com:443/admin/price_rules/count.json

Response status   Net::HTTPBadRequest (400)

Response body   {"errors":{"id":"expected String to be a id"}}

ActiveResource::BadRequest: Failed.  Response code = 400.  Response message = Bad Request.
```

**Comment by seashellski** [comment]
Same for `Location`; supports `Countable` but no bueno when called...

**Comment by seashellski** [comment]
This thread appears to confirm that it is a bug in the gem:

https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/where-is-admin-price_rules-count-json-489066

**Comment by jamiemtdwyer** [comment]
The Price Rules API doesn't support the `count` endpoint, along with some of the other resources in the API.

I believe the solution here would be to remove `extends Countable` from base.rb and have each resource explicitly include this if it is indeed countable. I can take a crack at it this week or next.

**Comment by mikeypotter** [comment]
@jamiemtdwyer Is it possible to get count endpoints on those two resources? This is blocking us from being able to backup those resources for Shopify customers.
