### ISSUE TITLE
Discount Code search

### ISSUE THREAD

**Issue by diwu86** [Shopify/shopify-api-ruby#403]
Hi, according to Shppify we have discount code search endpoint now . https://help.shopify.com/api/reference/discountcode#lookup.
Can we support this endpoint? This is very useful. 
Currently, in order to search discount code, we have to have a price_rule_id as the prefix. In the discount code search/lookup endpoint, we don't need price_rule_id anymore. I am not sure how to support this using current discount code model.

**Comment by TheInterwebbers** [comment]
+1

**Comment by Leteyski** [comment]
+1

**Comment by machadolab** [comment]
This is the one missing method keeping me from being able to use this gem for all my API needs.

**Comment by dan003400** [comment]
+1

**Comment by stujo** [comment]
Is there a way to call this API at all through the gem?

**Comment by dan003400** [comment]
I created a patch to the gem adding this ability. Add it to the gem by including the following method to an initializer.

```ruby
ShopifyAPI::DiscountCode.class_eval do
  def self.lookup(code)
    find(:one, from: '/admin/discount_codes/lookup.json?code=' + code)
  rescue ActiveResource::Redirection => e
    r = find(:one, from: e.response['Location'])
    unless r.nil?
      r.attributes[:price_rule_id] = %r{price_rules/([0-9]+)}.match(e.response['Location'])[1].to_i
      r.prefix_options[:price_rule_id] = %r{price_rules/([0-9]+)}.match(e.response['Location'])[1].to_i
    end
    r
  end
end
```

**Comment by ryana** [comment]
@dan003400 my hero!
