### ISSUE TITLE
Get products sorted (manual way) from a collection

### ISSUE THREAD

**Issue by benbonnet** [Shopify/shopify-api-ruby#418]
Went through all parts of code, searched a lot… I'm totally unable to understand how to retrieve products sorted while querying from a smart collection.

Is this available with specific parameters ?

**Comment by patrickemuller** [comment]
@benbonnet Did you find a solution? I have the same problem, but in my case I have custom_collections and I need to retrieve their products exactly how I defined them in the panel (manually).

**Comment by benbonnet** [comment]
Unfortunately it still seems to be unavailable. We decided to rely on tags (we have an external app the handle our categories, and tags are assigned automatically when they're added to a collection)

It is very far from being ok in that specific context, but product queries by tags are reliable so far

**Comment by patrickemuller** [comment]
@benbonnet thank you! It's a nice idea for a work around.

**Comment by nwtn** [comment]
@benbonnet I’d like to clarify — are you having this problem with the API in general (regardless of client), or with this gem in particular?

**Comment by patrickemuller** [comment]
@nwtn I tried only with the Gem. There is any way to see the URL generated for each resource before firing the request to the API?

**Comment by benbonnet** [comment]
@nwtn since the issue opened, I can say that we got in depth with the shopify api. The gem is okay if you already know very well the shopify api - it'll be easy to guess how to use the available options.

To be honest we've ended up calling the api directly with rest-client (what you're providing here under the hood), it helped us learn how shopify works

**Comment by nwtn** [comment]
> There is any way to see the URL generated for each resource before firing the request to the API?

I haven’t personally tried this, but it should be possible to use [collection_path](https://apidock.com/rails/ActiveResource/Base/collection_path/class) from ActiveResource (which this gem uses under the hood) to see the URLs that will be used. ActiveResource also supports [overriding validations](https://github.com/rails/activeresource/blob/master/lib/active_resource/base.rb#L109-L117), which you could probably use to take a look at the URL.

> I'd say it would be advisable to know first the rest api (going though the official doc). The logic (syntax) behind this gem then makes sense. But as an entrypoint, it's been a bit misleading for us

@benbonnet that’s great feedback, thanks. We’ll think about how we can make that expectation clearer.
