### ISSUE TITLE
Support for bulk update of metafields?

### ISSUE THREAD

**Issue by jagthedrummer** [Shopify/shopify-api-ruby#419]
The main API docs indicate that it's possible to set multiple metafields on a product with a single API call by including them as part of a product update. Is there anyway to do this through the ruby API?

https://help.shopify.com/api/reference/product#update

**Comment by wakproductions** [comment]
Not working for me either...

**Comment by wakproductions** [comment]
I've got a product like this:

```
v = ShopifyAPI::Variant.find(7760165896236)
v.metafield=[{namespace: 'product', key: 'product_id', value: '12345xyz', value_type: 'string'}]
v.save
#=> true

v = ShopifyAPI::Variant.find(7760165896236)

### v does not contain the metafield
```

**Comment by travishaynes** [comment]
@wakproductions Does this still happen if you fix the typo you have for `v.metafield`? It should be plural: `v.metafields`. If that doesn't work, I would try using a `ShopifyAPI::Metafield` instance in the array instead of a Hash.

**Comment by jagthedrummer** [comment]
```ruby
2.4.1 :010 > shopify_shop.metafields = [
  ShopifyAPI::Metafield.new({ namespace: 'my-app', value: 'hi', key: 'hello', value_type: 'string'})
]
 => [#<ShopifyAPI::Metafield:0x007fd91a3b9bb0 @attributes={...}, @prefix_options={}, @persisted=false>] 
2.4.1 :011 > shopify_shop.save
ActiveResource::ClientError: Failed.  Response code = 406.  Response message = Not Acceptable.
	from (irb):11
```

**Comment by wakproductions** [comment]
@travishaynes I made the correction you suggested and it now seems to work. Thanks!

@jagthedrummer I don't think you need to enclose it in a `ShopifyAPI::Metafield.new`... just make it the hash: `shopify_shop.metafields = [{ namespace: 'my-app', value: 'hi', key: 'hello', value_type: 'string'}]`

**Comment by onedanshow** [comment]
You can also bulk add metafields this way:

```
product = ShopifyAPI::Product.find(12341234)
product.update_attributes(metafields: [{ namespace: 'test', key: 'test', value: 1, value_type: 'integer' }])
```

Updating / overriding does not work this way, though.
