### ISSUE TITLE
Errors due to new undefined classes

### ISSUE THREAD

**Issue by mksm** [Shopify/shopify-api-ruby#486]
Seeing these new fields in some variants:

```
"presentment_prices"=>
         [#<ShopifyAPI::Variant::PresentmentPrice:0x000055fd933aea30
           @attributes=
            {"price"=>
              #<ShopifyAPI::Variant::PresentmentPrice::Price:0x000055fd933ae710
               @attributes={"currency_code"=>"USD", "amount"=>"39.95"},
               @persisted=true,
               @prefix_options={}>,
             "compare_at_price"=>
              #<ShopifyAPI::Variant::PresentmentPrice::CompareAtPrice:0x000055fd933adf68
               @attributes={"currency_code"=>"USD", "amount"=>"60.00"},
               @persisted=true,
               @prefix_options={}>},
           @persisted=true,
           @prefix_options={}>]},
```

Getting an undefined class error for `PresentmentPrice` and it's subclasses. Couldn't find documentation on `presentment_prices`.

**Comment by mksm** [comment]
Announced today: https://ecommerce.shopify.com/c/api-announcements/t/new-partner-beta-selling-in-multiple-currencies-with-shopify-payments-what-this-means-for-app-developers-547343?utm_campaign=ecomu&utm_medium=email&utm_source=subscription

**Comment by grcooper** [comment]
Hello! Could you provide more information on the errors you are seeing from this field, is there a field you are not able to access?

**Comment by mksm** [comment]
Errors:

- `uninitialized constant ShopifyAPI::Variant::PresentmentPrice`
- `uninitialized constant ShopifyAPI::Variant::PresentmentPrice::CompareAtPrice Did you mean? Comparable`

When manipulating a `ShopifyAPI::Variant` object with those new fields.

**Comment by mksm** [comment]
Gem version: 4.8.0
Raises: `uninitialized constant ShopifyAPI::Variant::PresentmentPrice`

```
Rails.cache.fetch(cache_key, expires_in: 10.minutes) do
  shop.with_shopify_session { ShopifyAPI::Product.find(id) }
end
```

**Comment by hengwoon** [comment]
We're getting the same as well. we are using the `readthis` gem for Redis Rails caching.

**Comment by imgenius-man** [comment]
I am facing the same issue. 
I was not caching any data and everything was working fine.

**Scenario**: Now I am using Redis to cache Customer Orders and Variants information and when I use that cached data it doesn't throw any exception but once I restart my server (development) or perform deployment (staging/production) after that it throws uninitialized constant issues like below.

`NameError (uninitialized constant ShopifyAPI::Order::TotalLineItemsPriceSet)`
`NameError (uninitialized constant ShopifyAPI::Order::TotalLineItemsPriceSet::ShopMoney)`
`NameError (uninitialized constant ShopifyAPI::Order::TotalLineItemsPriceSet::PresentmentMoney)`
`NameError (uninitialized constant ShopifyAPI::Order::TotalDiscountsSet)`
and so many uninitialized on `LineItem:: PriceSet`, `Refund:: RefundLineItem`, `ShippingLine::PriceSet` and `Customer:: DefaultAddress` etc.

Then I have to clear the cache manually and it comes back to normal.

I am using `shopify_app (13.0.0)`, `shopify_api (9.0.4)` and `Redis (4.2.2)`

**Comment by imgenius-man** [comment]
@katiedavis @nwtn can both of you help me on my issue? 👆

**Comment by abdulmunim1** [comment]
I am also having the same issue using `shopify_app (13.0)` gem.
Caching orders and variants raises different `uninitialized constant` errors such as:

> `NameError (uninitialized constant ShopifyAPI::Order::TotalLineItemsPriceSet)`
> `NameError (uninitialized constant ShopifyAPI::Order::TotalDiscountsSet)`

The only solution we have so far is to clean cache manually each time such error occurs.
