### ISSUE TITLE
Payouts API

### ISSUE THREAD

**Issue by woniesong92** [Shopify/shopify-api-ruby#509]
Hey! I have a few questions related to [Payouts](https://help.shopify.com/en/api/reference/shopify_payments/payout).

1. What class/method can I use to retrieve payout information?
2. Is there a way to see all the available methods in shopify_api gem? I tried searching [rubydoc](https://www.rubydoc.info/github/Shopify/shopify_api/ShopifyAPI/Receipt) but I don't think this is the right doc. What's the best way for me to see which method corresponds to a certain http api endpoint?
3. If I wanted to retrieve a resource using a url instead of a class method, is there a way to get the domain using `ShopifyAPI`? For example, instead of doing `https://username:password@shop.myshopify.com/admin/shop.json`, is there a way to do something like `ShopifyAPI::Shop.current.get('/admin/shop.json')`?

**Comment by marisveide** [comment]
Hey, thanks!
+1 from me for this.

**Comment by mrpunkin** [comment]
I'd also like to know how we can support the Payout API until it is built in to this codebase.

**Comment by jaybobo** [comment]
Searched around for about 90minutes before realizing that this gem just might not include the Payout API :(

**Comment by adipasquale** [comment]
hey ! I'm investigating doing something similar for the `POST /admin/api/#{api_version}/price_rules/#{price_rule_id}/batch.json` url which is not usable through this gem unfortunately. I'm not done yet, but I thought this could help you:

```
path = "customers.json"
shopify_path = ShopifyAPI::Base.api_version.construct_api_path(path)
url = ShopifyAPI::Base.site.to_s + shopify_path
res = RestClient.get(url, headers = ShopifyAPI::Base.headers)
JSON.parse(res.body)
```

not sure how robust this is though 🤷‍♂
