### ISSUE TITLE
Class not found for new multicurrency classes and others

### ISSUE THREAD

**Issue by jasonbuehler** [Shopify/shopify-api-ruby#517]
Hi, I am getting a class not found error for these classes: 

```
  ShopifyAPI::LineItem::OriginLocation
  ShopifyAPI::LineItem::DestinationLocation
  ShopifyAPI::Order::DiscountCode
  ShopifyAPI::ShippingLine::PriceSet
  ShopifyAPI::ShippingLine::PriceSet::ShopMoney
  ShopifyAPI::ShippingLine::PriceSet::PresentmentMoney
  ShopifyAPI::ShippingLine::DiscountedPriceSet
  ShopifyAPI::ShippingLine::DiscountedPriceSet::ShopMoney
  ShopifyAPI::ShippingLine::DiscountedPriceSet::PresentmentMoney
  ShopifyAPI::TaxLine::PriceSet
  ShopifyAPI::TaxLine::PriceSet::ShopMoney
  ShopifyAPI::TaxLine::PriceSet::PresentmentMoney
```

However when I fetch an API object such as an order, the classes then exist. I can't find where these are being defined in the repo, so I assume they are being dynamically generated. As such I don't think they are being defined at the right time. Is there a hook to run to generate the classes at load time so I don't run into these errors? 

Thanks

**Comment by forsbergplustwo** [comment]
Did you ever get this worked out @jasonbuehler ? I'm running into the same issue :/

**Comment by jasonbuehler** [comment]
@forsbergplustwo no, not really. If I remember correctly this was happening when AR was trying to deserialize an attribute that contained these objects, so I basically removed the serialize attribute macro from the AR models where they were defined. Not really a fix per se, but sufficient for getting me past the issue of the day. :P

**Comment by forsbergplustwo** [comment]
Makes sense, appreciate the workaround tip :)
