### ISSUE TITLE
GraphQL: products connections, query for ids

### ISSUE THREAD

**Issue by ghost** [Shopify/shopify-api-ruby#532]
Hey,

Analogue to the REST-Api products endpoint, it would be awesome if I could fetch multiple products by id via the graphql api.

**Comment by tylerball** [comment]
Hi,

You can use the [nodes](https://help.shopify.com/en/api/graphql-admin-api/reference/queryroot#nodes) field to query multiple objects via ID and you can also use aliases to query multiple products like; product1: `product(id:...) { ... } product2: product(id:...) { ... }`

**Comment by LemonAndroid** [comment]
Hey,

Thx!

Could `nodes` be used like the following:

```graphql
products(first: X) {
   nodes(ids: Y, Z) {
      id
     title
  }
}
```


Or is it independent of the `products` collection field? If so, how would `nodes` be used properly?

**Comment by nwtn** [comment]
@LemonAndroid it would be like this:

```graphql
{
  nodes(ids: ["gid://shopify/Product/123", "gid://shopify/Product/456"]) {
    ...on Product {
      id
      title
    }
  }
}
```

**Comment by nwtn** [comment]
(Keeping the issue open for now because we should document this better)

**Comment by LemonAndroid** [comment]
what is `...on X`? i've never seen this syntax?

**Comment by nwtn** [comment]
These are [inline fragments](https://graphql.org/learn/queries/#inline-fragments)

**Comment by oluosiname** [comment]
This worked fine for me @nwtn when I tried it with the graphql app but I get an error when I try to implement in my rails app.
Error is `GraphQL::Client::ValidationError: uninitialized constant on`

> @LemonAndroid it would be like this:
> 
> ```graphql
> {
>   nodes(ids: ["gid://shopify/Product/123", "gid://shopify/Product/456"]) {
>     ...on Product {
>       id
>       title
>     }
>   }
> }
> ```

**Comment by little-gui** [comment]
```graphql
{
  nodes(ids: ["gid://shopify/Product/123", "gid://shopify/Product/456"]) {
    ...on Product(query: "some title") {
      id
      title
    }
  }
}
```
Is this possible?

**Comment by chrisworman-pela** [comment]
@nwtn Can you repeat your sample query without using the product fragment please.
