### ISSUE TITLE
Remove code related to `FulfillmentRequest`

### ISSUE THREAD

**Issue by justinkrol** [Shopify/shopify-api-ruby#547]
### Summary

The `FulfillmentRequest` resource no longer exists in `Shopify/shopify`, so it should be removed from this gem as well.

Here are some relevant PRs in `Shopify/shopify`: [PRs to remove FulfillmentRequest](https://github.com/Shopify/shopify/pulls?q=is%3Apr+author%3Ajustinkrol+FulfillmentRequest+is%3Aclosed)

### Related files 
- [ ] [lib/shopify_api/resources/fulfillment_request.rb](https://github.com/Shopify/shopify_api/blob/master/lib/shopify_api/resources/fulfillment_request.rb)
- [ ] [test/fulfillment_request_test.rb](https://github.com/Shopify/shopify_api/blob/master/test/fulfillment_request_test.rb)
- [ ] [test/fixtures/fulfillment_request.json](https://github.com/Shopify/shopify_api/blob/master/test/fixtures/fulfillment_request.json)

Notes
* Removing this should not impact any apps with the gem installed, as the resource does not exist.
* There are no related docs, so there is nothing to do on that front.

cc @stephenminded

**Comment by MalazAlamir** [comment]
Any updates on this?
