### ISSUE TITLE
undefined method `construct_api_path' for nil:NilClass

### ISSUE THREAD

**Issue by michaelnwani** [Shopify/shopify-api-ruby#574]
I upgraded from shopify_api `v6.0.0` to `v7.0.1` 5 days ago, while upgrading from Rails `v5.2` to `v6.0.0.rc1` 5 days ago and just noticed this issue (if the cause is around the update).

When I run: `ShopifyAPI::Product.all`

I am immediately met with this error: 

```
NoMethodError: undefined method `construct_api_path' for nil:NilClass
from /Users/michaelnwani/.rvm/gems/ruby-2.6.2/gems/shopify_api-7.0.1/lib/shopify_api/resources/base.rb:84:in `prefix'
```

Downgrading back to `v6.0.0` fixes the issue.

Thoughts?

**Comment by miahabdu** [comment]
+1

**Comment by resistorsoftware** [comment]
When I use the command line tool Shopify CLI, it also fails in exactly the same manner. Clearly the Shopify API gem has some new issue?

    p = ShopifyAPI::Product.count
    NoMethodError: undefined method `construct_api_path' for nil:NilClass
    from /Users/dlazar/.rvm/gems/ruby-2.6.2/gems/shopify_api- 
    7.0.1/lib/shopify_api/resources/base.rb:84:in `prefix'

**Comment by resistorsoftware** [comment]
This can be fixed in shopify_cli gem by adding the versioning to the connection in method site_from_config(config)

    ShopifyAPI::Base.api_version = '2019-04'

**Comment by brianflanagan** [comment]
@resistorsoftware Thanks -- was scratching my head.

**Comment by resistorsoftware** [comment]
Shopify acknowledged the shortcoming and provided information that they are now aware of the issue and working to release updated code that ensures this error disappears.

**Comment by mixturestylekah** [comment]
The same situation happened to me, is there a solution?

error.log
```
NoMethodError (undefined method `construct_api_path' for nil:NilClass)

```

Gemfile
```
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.3'

...

gem 'shopify_app'
gem 'activeresource', github: 'rails/activeresource'
```

Gemfile.lock
```
shopify_api (7.0.1)
activeresource (>= 4.1.0, < 6.0.0)
graphql-client
rack
shopify_app (9.0.3)
browser_sniffer (~> 1.1.2)
omniauth-shopify-oauth2 (~> 2.1.0)
rails (>= 5.0.0)
shopify_api (>= 7.0.0)
```

**Comment by iamricks** [comment]
Any updates on this issue? Pretty much makes 7.0 Unusable.

**Comment by sirtawast** [comment]
> Any updates on this issue? Pretty much makes 7.0 Unusable.

Did you try [this](https://github.com/Shopify/shopify_api/issues/574#issuecomment-489718270)? Worked for me!

**Comment by markdavies** [comment]
Any fix for this? This makes the latest version of shopify_app completely unusable.

**Comment by nwtn** [comment]
Are you still getting this error even when following the instructions in the README related to API versioning?

https://github.com/Shopify/shopify_api#getting-started

e.g.:

> For a private App you just need to set the base site url as follows:
>
> shop_url = "https://#{API_KEY}:#{PASSWORD}@#{SHOP_NAME}.myshopify.com"
> ShopifyAPI::Base.site = shop_url
> ShopifyAPI::Base.api_version = '<version_name>' # find the latest stable api_version [here](https://help.shopify.com/api/versioning)

I can reproduce when api_version isn’t specified, but explicitly specifying api_version is a requirement for v7+ of the gem.

**Comment by markdavies** [comment]
Ah, it looks like my issue is with shopify_app. They have an api_setting config variable which might not be used with shopify_api

**Comment by benbonnet** [comment]
It does not seem to plays nicely within the shopify_app gem use; at least I'm unaware of the workaround

Having the following base module :

```
module GraphqlClient
    GRAPHQL_CLIENT = ::ShopifyAPI::GraphQL.new
end
```

```
class AllTags
  include GraphqlClient
  ClassQuery = GRAPHQL_CLIENT.parse <<-'GRAPHQL'
    {
      shop {
        productTags(first: 250) {
           ...
        }
    }
  GRAPHQL

  def call
     GRAPHQL_CLIENT.query(ClassQuery)
  end
end
```

The rails app won't start correctly as everything is loaded on startup. How would use the graphql api within a partner app context ? What would be the correct class structure ?

**Comment by LouiseEH** [comment]
@benbonnet Did you find a solution? I am struggling with what seems to be a similar issue. When I start the server locally there are no problems, but when the server is started via Heroku, the server crashes:

NoMethodError: undefined method `path=' for nil:NilClass
 /app/vendor/bundle/ruby/2.5.0/gems/shopify_api-8.1.0/lib/shopify_api/resources/graphql.rb:10:in `initialize'
