### ISSUE TITLE
ShopifyAPI::Fulfillment.new says ActiveResource::ResourceInvalid (Failed.)

### ISSUE THREAD

**Issue by ayazahmadtarar-pikessoft** [Shopify/shopify-api-ruby#576]
I am creating a new fulfilment against order in ruby
```
 fulfill = ShopifyAPI::Fulfillment.new( :params => {:order_id => t.shopify_order_id})
          fulfill.tracking_numbers = tracking_numbers
          fulfill.tracking_company = shipping_company
          fulfill.tracking_urls = tracking_links
          fulfill.prefix_options = { :order_id => t.shopify_order_id }
          fulfill.save
  

```
fulfill.errors.full_messages.to_sentence is returing nill and 

```
2.5.0 :014 > fulfill.save
 => false 
2.5.0 :015 > fulfill.save!
Traceback (most recent call last):
        9: from bin/rails:6:in `<main>'
        8: from bin/rails:6:in `require'
        7: from /var/rails/sendoso/shared/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/commands.rb:17:in `<top (required)>'
        6: from /var/rails/sendoso/shared/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        5: from /var/rails/sendoso/shared/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:68:in `console'
        4: from /var/rails/sendoso/shared/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/commands/console.rb:9:in `start'
        3: from /var/rails/sendoso/shared/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/commands/console.rb:110:in `start'
        2: from (irb):15
        1: from /var/rails/sendoso/shared/bundle/ruby/2.5.0/gems/activeresource-4.1.0/lib/active_resource/base.rb:1288:in `save!'
ActiveResource::ResourceInvalid (Failed.)
```
How do I fix these issue. This process is creating webhook for other store but on specific store its generating issue

**Comment by mantgomery** [comment]
same issue. any idea?

**Comment by mantgomery** [comment]
in my case 
However, if an order is refunded or if any of its individual line items are refunded, then the order can't be fulfilled.

**Comment by resistorsoftware** [comment]
You have to provide a location_id when you create a fulfillment.

**Comment by brandnamewater** [comment]
You need a location_id.  My issue is that orders aren't even passing location_id's for some reason anymore (maybe an update)... From my understanding, we need to create a fulfillment service but I am unsure how to do this

**Comment by lagunasolutions** [comment]
@brandnamewater how do you get your orders? On my side I use

`ShopifyAPI::Order.find(:all, params: {limit: 250, created_at_min:min_creation_date, created_at_max:max_creation_date, page: page, financial_status: "paid", fulfillment_status: "unshipped", fields: "id,name,email,**location_id**,created_at,note,discount_codes,shipping_address,line_items,customer"})`

the location_id gets returned properly. Did you succeed to fulfill your order? I'm having similar problem even tough I have the correct location_id.

**Comment by lagunasolutions** [comment]
**UPDATE**

1. I added **write_orders** in my shopify_app.rb:   
`config.scope = "read_orders, write_orders, read_products"`
2. I uninstalled and re-installed the app to have the correct permissions (Dont know if there is a better way).
3. The **location_id** in my case is always the same, if it is not listed in your order data, make sure your address and locations are properly set in the Shopify Admin. One other way to find your location_id (if you only have one and know for sur it will never change) is to go in an order page and copy the url of the Mark as fullfilled button, it should give you something like /admin/orders/15137750057/fulfill_and_ship?fulfill_only=true&fulfillment_service_handle=manual&**location_id=7878869050**&requires_shipping=true

here is my final ruby code

`     f = ShopifyAPI::Fulfillment.new(
          :order_id => ORDER_ID,
          :location_id => LOCATION_ID,
          :notify_customer => true
        )
        #f.tracking_numbers = tracking_numbers
        #f.tracking_company = shipping_company
        #f.tracking_urls = tracking_links
        f.prefix_options = { :order_id => ORDER_ID }
        f.save`

Hope this helps!

**Comment by resistorsoftware** [comment]
Orders do NOT have a location ID useful for all fulfillments. If you look that up, the order location ID is where an order was placed which could have zero to do with where the items sold come from to be fulfilled. Answers here that insinuate the order location ID is interesting are missing the main point for fulfillments. **Items have a location ID** that is not necessarily the same as the order location ID.

At the order level, you get a variant ID for a line item. You use that to get the variant's inventory_item_id. With that you can get the correct **location ID** of the inventory item to make a fulfillment. When you use the **location_id** of the **order**, that is the location where the order was placed, which could mean WWW, POS or anything else with a location.

Just a PSA or FYI...
