### ISSUE TITLE
Shopify payment transaction

### ISSUE THREAD

**Issue by SaimonL** [Shopify/shopify-api-ruby#590]
I was just wondering if this gem has Shopify payments transaction API call.
I am not talking about order transactions like the one here "https://github.com/Shopify/shopify_api/blob/master/test/transaction_test.rb"

I am referring to "https://help.shopify.com/en/api/reference/shopify_payments/transaction" which also has fee as well.

**Comment by fullstackdb** [comment]
Hi,
+ 1 on that.
