### ISSUE TITLE
Wrong Number of Arguments: ShopifyAPI::Customer.search

### ISSUE THREAD

**Issue by bstarr322** [Shopify/shopify-api-ruby#598]
Hi,

I'm going to search customer by email.
```
shop = Shop.first
shop.with_shopify_session do
     @shopify_customer = ShopifyAPI::Customer.search({ query: 'email:obulten22@gmail.com' })
end
```

but this gives an error:
`wrong number of arguments (given 2, expected 4)`

and shopify_api version is `5.2.4`

Could you please let me know what I am wrong?

Regards

**Comment by bstarr322** [comment]
Even find by id is not working. this gives same error:
`customer = ShopifyAPI::Customer.find(id)`
`wrong number of arguments (given 2, expected 4)`

**Comment by tanema** [comment]
You are using quite an old version of shopify_api that will not work soon, I recommend updating before proceeding.
