### ISSUE TITLE
Filter by fulfillment_status return all order

### ISSUE THREAD

**Issue by huynhit-92** [Shopify/shopify-api-ruby#608]
Hi there
i want to search orders with fulfillment_status : shipped and partial but it return all orders.
Am I wrong or this gem does not support for multi status search ?

Gem version: **5.1.0**
Query:
```
ShopifyAPI::Order.find(:all, params: { fulfillment_status: 'shipped,partial' }).count
```

**Comment by menporulporiayalan** [comment]
Hi @huynhit-92 

I think the Shopify itself does not support multi-status search.  I have tried the above URL in the postman.  It just returned only a partial order.

`https://myshopname.myshopify.com/admin/orders.json?limit=2&fulfillment_status=partial`

But, When I try a multi-status search like below URL, it doesn't seems work. 

`https://myshopname.myshopify.com/admin/orders.json?limit=2&fulfillment_status=shipped,partial`
