### ISSUE TITLE
Address resource needs prefix

### ISSUE THREAD

**Issue by nickmealey** [Shopify/shopify-api-ruby#634]
It seems to me that the `Address` resource doesn't allow for `prefix_options` when dealing with a customer. Should there be another class for `CustomerAddress` where a customer prefix would be added?
```
module ShopifyAPI
  class CustomerAddress < Base
    init_prefix :customer
  end
end
```

Then `customer.addresses` could return `CustomerAddress` instances. I realize that an `Address` could be used for multiple purposes, but I would expect the following code to work, but it 404s:
```
first_address = ShopifyAPI::Customer.find(123456789).addresses.first
# >>> { id: 65432345, address1: .... }

first_address.save
# >>> Resource not found
```

For now, I've monkey patched this, but maybe I'm not understanding the intention here.

**Comment by JonathanFrias** [comment]
I have this issue as well. This is what my monkey patch looks like for anybody looking for a copy/paste solution

config/initializers/shopify.rb
```ruby
# https://github.com/Shopify/shopify_api/issues/634
class CustomerAddress < ShopifyAPI::Address
  init_prefix :customer

  self.element_name = "address"
end

class ShopifyAPI::Customer
  def addresses
    (attributes['addresses'] || []).map do |unprefixed_address|
      address = CustomerAddress.new
      address.load(unprefixed_address.attributes)
    end
  end
end
```
