### ISSUE TITLE
Prevent sending customer email when create an order using Graphql

### ISSUE THREAD

**Issue by maxwang096** [Shopify/shopify-api-ruby#642]
Hi, I have created an order using GraphQL Admin API.
`draftOrderCreate mutation` and `draftOrderComplete mutation`
But after order is created, an order confirmation email is sent to the customer.
It looks like it is possible to stop preventing using REST Admin API.

Can we prevent sending emails using GraphQL Admin API?

**Comment by SunboX** [comment]
This seems still to be an issue with version 2023-04? Is there any way to prevent sending a notification to customers?

**Comment by svespinup** [comment]
In this topic it is suggested to add the (draft)order **without user email**, then to complete it and after this to add the user email.

In my case I also use the GraphQL Admin API mutations draftOrderCreate and draftOrderComplete . So:
1. draftOrderCreate without adding the parameter 'email'
2. draftOrderComplete with the draft order ID returned from draftOrderCreate
3. edit Order to attach the user (currently working on this)

I am still testing, but it looks to work and does not send mail to the user on completion.

https://community.shopify.com/c/shopify-discussions/is-it-possible-not-to-send-customer-an-email-when-creating-draft/td-p/1033946
