### ISSUE TITLE
Refund unfulfilled

### ISSUE THREAD

**Issue by miguelrod** [Shopify/shopify-api-ruby#667]
Hi all.

I've been testing refunds and I think I found an issue.
**Scenario.**
I have an order for 20 keyboards (all same item, same product).
I have fulfilled 10 of those 20.
Now when I go into the refund page I can refund the fulfilled items or the unfulfilled items.
My question is: how can I use the API to do the same?
I can see `no_restock, cancel, return`.
But if I want to use `no_restock` how do I distinguish between unfulfilled and fulfilled on the same item ? 
So far the behaviour has been it refunds always the fulfilled ones first and then proceeds to refund the unfulfilled ones.
I can see on the web interface that there's an extra parameter: `removal` but not available on on the api nor graphql.
Been going crazy with this...

Thanks,
Miguel

**Comment by jarredszabadi** [comment]
Posted in slack, will repost this here. 


We deal with this in the new POS that we are building.
We do allow merchants to select if they want to refund and or restock the fulfilled 
quantity or the unfulfilled quantity (or both!)

Here's how we do it:

- we're using graphql but it should also be possible in rest

- you will create 2 refundLineItem inputs for the same partially fulfilled line item

- in the first refundlineItem you will have to have the quantity and restockType appropriate for the unfulfilled items

- in the second refundLineItem you will have the quantity and restock type for the fulfilled items.

- the onus is on you, the api user, to ensure you have the correct quantity and restockType selected 

This is the input for a refund that had 1 line item with 4 quantity. 2 were fulfilled and 2 were unfulfilled. You will see that there are 2x refundLineItems (red box) both referencing the same lineItem from the original order (green boxes). In the orange boxes you can see the restockType specified

<img width="842" alt="Screen Shot 2020-01-14 at 6 20 21 PM" src="https://user-images.githubusercontent.com/3138299/72392483-3bbc2300-36fe-11ea-86ae-8fb380e6aea8.png">

**Comment by miguelrod** [comment]
Hi @jarredszabadi thank you so much for the reply.

On this scenario you are returning the fulfilled and cancelling the unfulfilled, but my issue is:

what if want to refund both with `no_restock` ? Or even just one unfulfilled ? How does it know how to refund one unfulfilled and not a fulfilled given that the parameters will be the same ?


Again, thank you :)
Miguel

**Comment by jarredszabadi** [comment]
If you don't want to restock unfulfilled items you should use 'cancel'. If you don't want to restock the fulfilled items you should use 'no_restock'

**Comment by miguelrod** [comment]
Here's how I understood it:

- **no_restock**: Refunding these items won't affect inventory. 
  - I can refund either **fulfilled or unfulfilled** that stock won't change
- **cancel**: The items have not yet been fulfilled. The canceled quantity will be added back to the available count. The number of fulfillable units for this line item will decrease.
  - Only for **unfulfilled**: the quantity will be added back to stock
- **return**: The items were already delivered but will be returned to the merchant. The returned quantity will be added back to the available count. The number of fulfillable units for this line item will remain unchanged.
  - Only for **fulfilled**: the quantity will be added back to stock

I'll do a few more tests to make sure I have the correct values for each scenario

**Comment by jarredszabadi** [comment]
Depending on your api version you should be able to pass in "removal" as an input. I do believe that will be key.

If you can try something like this:

```
Refund {
   refundLineItems: [
      {lineItemId: 1, quantity: 5, restockType: no_restock, removal: false}
      {lineItemId: 1, quantity: 5, restockType: no_restock, removal: true}
   ]
}
```
First refundLineItem with removal = false would be for your fulfilled items.
Second refundLineItem with removal = true would be for your unfulfilled items.
Change the quantity how you see fit, so if you did quantity: 3 for your second line item there it should know to refund just 3 of the unfulfilled items.

**Comment by miguelrod** [comment]
Did a quick check with 2020-04(next release) and seems that removal is not yet available for graphql nor  REST API.

![Screen Shot 2020-01-15 at 00 34 28](https://user-images.githubusercontent.com/1130291/72394880-a76ab400-372f-11ea-8c6c-d09ad4f2fe99.png)

(also tried on terminal and returns invalid parameter `removal` on graphql and just ignores it on rest)

Maybe soon ?

**Comment by vhfsc** [comment]
Hello, 
any news about this subject, being able to choose in the API if we are refunding from the fulfilled or unfulfilled items of the order ?

**Comment by miguelrod** [comment]
Don't think there's been an update yet...
