### ISSUE TITLE
Ability to use sections api

### ISSUE THREAD

**Issue by anark** [Shopify/shopify-api-ruby#680]
I'm trying to use this gem with the new sections api's(https://help.shopify.com/en/api/reference/online-store/sections).  What would be needed to add these api's?

**Comment by tanema** [comment]
I am pretty sure that sections are just theme assets so you should be able to use ShopifyAPI::Asset with the appropriate theme asset file paths and it should work.

**Comment by tolgap** [comment]
@tanema what? Sections API is part of the REST API documentation 😅. Its built to actually not rely on themes anymore, and programmatically add sections into the Shopify Theme Editor.

**Comment by tanema** [comment]
Sorry, I answered this to quickly and only thought about section files. (I am obviously not a theme expert) Currently this library does not support them and the Online Store team should add them in the future when the API stabilizes but it is pretty easy to create your own active resource access. Just inherit from ShopifyApi::Base
