### ISSUE TITLE
Rails 6 inflection error on ActiveResource::Formats::XmlFormat

### ISSUE THREAD

**Issue by EmmaB** [Shopify/shopify-api-ruby#683]
When I make a call such as `ShopifyAPI::Collect.create(collect)` or `ShopifyAPI::CustomCollection.find(collection.id).update_attributes(published: nil)` and get an error response, I get the following: 

```
NameError (uninitialized constant ActiveResource::Formats::XMLFormat)
Did you mean?  ActiveResource::Formats::XmlFormat
```

This is because my `inflections.rb` initializer contains: 

```
ActiveSupport::Inflector.inflections do |inflect|
  inflect.acronym "XML"
  ...
end
```

The call to ActiveResource should probably insulate itself from local inflection overrides, shouldn't it?

**Comment by tanema** [comment]
Why do you think this has to do with the Inflections? I am not sure why active resource would have any interaction with ActiveSupport::Inflector at all currently. What lead you to believe this?

**Comment by EmmaB** [comment]
Well, the error is pretty clear: it's trying to call `ActiveResource::Formats::XMLFormat`, and it can only be doing that because our repo defines `XML` as an acronym. But the class is [`XmlFormat` ](https://www.rubydoc.info/github/rails/activeresource/ActiveResource/Formats/XmlFormat). 

Maybe it jumps out to me because I saw lots of these type of errors when upgrading from Rails 5 to 6, getting Zeitwerk to work.

**Comment by bittersweet** [comment]
I wanted to add some context here as I found this issue via google (related to ActiveSupport::Inflector ActiveResource queries), I am not using `shopify_api` myself though.

We also recently defined the `XML` acronym for rails 6/zeitwerk related purposes. ActiveResource indeed uses inflections to autoload the xml and json formatters:
https://github.com/rails/activeresource/blob/dedecf90996622776b7aa0e54957ffc8fb3ac2f9/lib/active_resource/formats.rb#L3-L14

```ruby
    # Lookup the format class from a mime type reference symbol. Example:
    #
    #   ActiveResource::Formats[:xml]  # => ActiveResource::Formats::XmlFormat
    #   ActiveResource::Formats[:json] # => ActiveResource::Formats::JsonFormat
    def self.[](mime_type_reference)
      ActiveResource::Formats.const_get(ActiveSupport::Inflector.camelize(mime_type_reference.to_s) + "Format")
    end
```

So if you have defined `XML` in the inflections list, that results in:

```
>> ActiveSupport::Inflector.camelize("xml".to_s) + "Format"
=> "XMLFormat"
```

For our project we have worked around it with a quick patch:

```
module ActiveResource
  module Formats
    XMLFormat = XmlFormat
  end
end
```

**Comment by odlp** [comment]
Posting to improve the odds of a hit for anyone searching; this impacts the JSON format too when an inflection is configured

```
NameError: uninitialized constant ActiveResource::Formats::JSONFormat
Did you mean?  ActiveResource::Formats::JsonFormat
```
