### ISSUE TITLE
Order save failing

### ISSUE THREAD

**Issue by jbutler-lifefuels** [Shopify/shopify-api-ruby#710]
I have an order that had an invalid email address and it was failing to create the order. I have fixed the order and I am trying to repost it and it fails to save. The only error I get back is 'Failed', is there a way to tell what the actual error is?

```
begin
    shopify_order = ShopifyAPI::Order.new( ... )
    shopify_order.save
rescue Exception => e
    log.error { "Unable to create a Shopify Order: #{e}" }
end
```

**Comment by marschattha** [comment]
Try checking `shopify_order.errors.messages`

**Comment by jbutler-lifefuels** [comment]
It just says 'Failed'

**Comment by marschattha** [comment]
Can you show the values your using to build the new order?

Or you can try scrubbing one attribute at a time and see which is causing the issue.

Might help posting your request header details as Shopify staff can check the request issue from their end using that.

**Comment by jbutler-lifefuels** [comment]
We ended up putting through the order manually so as not to hold it up
since it happened last week. I have noticed this happen before and it seems
to happen when the user's email address is not valid (ex: gmail.con). I
have fixed it to prevent this going forward on my end but it's something
worth noting.
