### ISSUE TITLE
NoMethodError: undefined method `client' for ShopifyAPI::GraphQL:Class

### ISSUE THREAD

**Issue by ayushkanoongo** [Shopify/shopify-api-ruby#724]
I am using gem version 9.0.0.
sometimes it works fine but sometimes I got an error that the client is an undefined method in line
`ShopifyAPI::GraphQL.client`

**Versions Breakdown**

> Rails(5.2.4.1)
> Ruby(2.5.1)
> Shopify App(11.6.0)
> Shopify Api(9.0.0)

**Comment by tanema** [comment]
Can you give us more code and more context? It is hard to tell what you are doing and what is happening with this.
