### ISSUE TITLE
Managing content for the the Open Source page

### ISSUE THREAD

**Issue by andyw8** [Shopify/shopify-api-ruby#740]
The page at https://shopify.github.io/shopify_api/ is a public 'landing' page for the shopify_api gem.

It's based on the content from the gem's README but hadn't been updated for some time and so became stale.

In #739 we're updating it, but we still need a better long term solution, or it will become stale again.

Some options to consider:
* Have a fully automated way of updating the docs, e.g. a GitHub action
* Have a schedule reminder for the team to update the docs, e.g. quarterly
* Create an alternate landing page which gives less detailed, higher-level overview of the library which would be less likely to become stale.

cc @attaboy

**Comment by andyw8** [comment]
https://github.com/benbalter/jekyll-readme-index - this might also be a solution, although I'm not sure if it will work on GitHub Pages.

**Comment by attaboy** [comment]
I would vote for #3 personally: use the README as a high-level overview and launch point for the docs. I don't think detailed docs belong in a README, and having one long doc both makes it harder to read and harder to maintain IMO.
