### ISSUE TITLE
Update Order Fulfillment Status

### ISSUE THREAD

**Issue by Bilal-Abbas** [Shopify/shopify-api-ruby#757]
Is it possible to update the order financial status to fulfilled through this gem

I have used

```
session = ShopifyAPI::Session.new(domain: company.ext_reference_domain,
          token: company.ext_reference_token, 
          api_version: '2019-04')
session = ShopifyAPI::Base.activate_session(session)
order = ShopifyAPI::Order.all(params: {id: self.order_ref_id})
```

but if I tried to update status like we always do with rails it doesn't allow me to do that.

Any help !!!

**Comment by tanema** [comment]
What is the error you get?

**Comment by Bilal-Abbas-Gigalabs** [comment]
Hi,
I figure this out by myself.
We need store location to fulfil any order.
We can close this issue as I fixed by quite a while ago.
If someone still need help, he/ she can open this up.
