### ISSUE TITLE
Pulling order details then saving gives a Bad Request error

### ISSUE THREAD

**Issue by lorismaz** [Shopify/shopify-api-ruby#759]
I have an issue that I have difficulties to troubleshoot. My code is supposed to just get an order from its id, then set a note_attribute, and finally save, something like this:

```ruby
begin
    shopify_order = ShopifyAPI::Order.find(webhook[:id])
    shopify_order.note_attributes << ShopifyAPI::NoteAttribute.new(
          name: 'ftp_status',
          value: 'uploaded'
        )
    shopify_order.save
rescue Exception => e
    log.error { "Unable to update Shopify Order: #{e}" }
end
```

Now it works pretty well, but one in 50 orders can't save, I get an `ActiveResource::BadRequest: Failed. Response code = 400. Response message = Bad Request (434: unexpected token at '...'` 

```
ActiveResource::BadRequest: Failed. Response code = 400. Response message = Bad Request (434: unexpected token at '{"id":xxx,"title":"Livraison offerte dès 60€ d'achats","price":"0.00","cod...
```

or 

```
ActiveResource::BadRequest: Failed. Response code = 400. Response message = Bad Request (783: unexpected token at '{"order":{"id":xxxx,"email":"xxx@gmail.com","closed_at":null,"creat...
```

When troubleshooting, I discovered that for those orders that fails, just loading the order and saving fails with the same error, regardless of the note_attributes set or not, so my order have something in it that makes it fail:

```ruby
shopify_order = ShopifyAPI::Order.find(webhook[:id])
shopify_order.save # <- this still fails, without event changing the order just pulled
```

These orders are created by a real user, not a script. I can't find something redundant in orders that fails, except that they tend to have more than 8 products in the order. This happens in production, so I don't know how to reproduce it locally. When logged in console in production, I can reproduce the error if the order update failed once, by just loading the order and saving it. The store is in French so products and customers use some accented characters but I doubt it's the issue here.

## Log example
Here is a longer example of log, it gets truncated at the end :

```
Failed.  Response code = 400.  Response message = Bad Request (434: unexpected token at '{"id":xxxx,"title":"Livraison offerte dès 60€ d'achats","price":"0.00","code":"Livraison offerte dès 60€ d'achats","source":"shopify","phone":null,"requested_fulfillment_service_id":null,"delivery_category":null,"carrier_identifier":null,"discounted_price":"0.00","price_set":{"shop_money":{"amount":"0.00","currency_code":"EUR"},"presentment_money":{"amount":"0.00","currency_code":"EUR"}},"discounted_price_set":{"shop_money":{"amount":"0.00","currency_code":"EUR"},"presentment_money":{"amount":"0.00","currency_code":"EUR"}},"discount_allocations":[],"tax_lines":[{"title":"TVA","price":"0.00","nes":[{"title":"TVA","price":"0.00","rate":0.2,"price_set":{"shop_money":{"amount":"0.00","currency_code":"EUR"},"presentment_money":{"amount":"0.00","currency_code":"EUR"}}}]}],"billing_address":{"first_name":"Zoé","address1":"xxx rue Hélène xxx ","phone":"0x xx xx xx xx","city":"xxxx","zip":"xxxx","province":null,"country":"France","last_name":"xxxx-xxxx ","address2":"","company":null,"latitude":xx.xxxx,"longitude":x.xxxx,"name":"xxxx xxxx-xxxx ","country_code":"FR","province_code":null},"shipping_address":{"first_name":"xxxx","address1":"xxx rue Hélène xxx","phone":"0x xx xx xx xx","city":"xx","zip":"xxxxx","province":null,"country":"France","last_name":"xxx-xxxx ","address2":"","company":null,"latitude":xxx,"longitude":xxx"name":"xxxx ","country_code":"FR","province_code":null},"client_details":{"browser_ip":"xxxx","accept_language":"fr-fr","user_agent":"Mozilla/5.0 (iPhone; CPU iPhone OS 13_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Mobile/15E148 Safari/604.1","session_hash":"xxx","browser_width":375,"browser_height":635},"payment_details":{"credit_card_bin":"xxxx","avs_result_code":"Y","cvv_result_code":"M","credit_card_number":"•••• •••• •••• xxxx","credit_card_company":"American Express"},"customer":{"id":xxxx,"email":"xxxx@gmail.com","accepts_marketing":true,"created_at":"2019-09-23T19:14:57+02:00","updated_at":"2020-07-19T23:39:06+02:00","first_name":"xxxx","last_name":"xxxx-xxxx","orders_count":1,"state":"enabled","total_spent":"151.00","last_order_id":xxxx,"note":null,"verified_email":false,"multipass_identifier":null,"tax_exempt":false,"phone":null,"tags":"Receiving updates in Messenger","last_order_name":"#xxxx","currency":"EUR","accepts_marketing_updated_at":"2019-09-23T19:14:57+02:00","marketing_opt_in_level":"single_opt_in","tax_exemptions":[],"admin_graphql_api_id":"gid://shopify/Customer/xxxx","default_address":{"id":xxxx,"customer_id":xxxx,"first_name":"xxxx","last_name":"xxxx-xxxx ","company":null,"address1":"xxxx rue Hélène xxxx ","address2":"","city":"xxxx","province":null,"country":"France","zip":"xxxx","phone":"0x xx xx xx xx","name":"xxx xxxx-xxxx ","province_code":null,"country_code":"FR","coun').
```

**Comment by paulomarg** [comment]
Thanks for reporting this in @lorismaz, this looks like it might be a JSON syntax error, so the API code might be failing to convert some of the data it got back from the server when saving the Order again.

It would be very helpful if we could see exactly where the error is in the JSON. The JSON code in the log you got seems to be valid up to where it got truncated, so ideally we'd want to check the entire object for errors.

You can grab the JSON for the object that's failing by running `shopify_order.as_json`. Would it be possible for you to get the JSON for the order when the update fails? That way we could check where that syntax error might be happening and fix it.

**Comment by lorismaz** [comment]
If I get the shopify_order.to_json (.as_json returns me a ruby hash), and test it, it's a valid json. I can share the json but I need to go through 2000 lines to remove personal information it can takes time. Also if I scrub personal info I might scrub something that was creating the problem. How can I share this securely ?

**Comment by paulomarg** [comment]
Hi @lorismaz, those are good points. If the JSON generated by the API code is valid, then the problem is most likely on our end.

Would you be OK with sharing your shop domain, API key, the JSON and request time of one such failure to my email at paulo.margarido@shopify.com? With this info I can follow up on the request and figure out why it's failing.

**Comment by paulomarg** [comment]
One thing that occurred to me is that you mentioned this usually happens on orders with many products.

The fact that the JSON is valid in the code but seems to be invalid after it is sent could indicate that it is getting cut in the HTTP request because it's too long.

I'll continue to investigate, but I'd also recommend you check whether your server is actually sending the full JSON data through.

**Comment by sshaw** [comment]
> ActiveResource::BadRequest: Failed. Response code = 400. 
> ...
>  I can't find something redundant in orders that fails, except that they tend to have more than 8 products in the order.

Maybe you're hitting Shopify's HTTP servers' max body size.

**Comment by paulomarg** [comment]
I was thinking the same thing, but I tested this with similar size JSONs and I didn't manage to reproduce the issue (the requests worked just fine). So at the very least it's not something that happens frequently.

As an update to people who come by this issue, I have requested a bit more debugging information from Loris which will hopefully allow me to pinpoint the issue and fix it.

**Comment by lorismaz** [comment]
Hey @paulomarg, so I can't reproduce the error with more than 500 orders that went through since last time, and I haven't changed my code. I can't find headers info for an error call from previous calls, what can I do to help ?

**Comment by paulomarg** [comment]
Hey @lorismaz, I think at this point we will need to keep watching for when it does happen, since I couldn't reproduce it myself yet. If you can get the request id for a failing request I can see exactly why it failed and help me identify the root cause.
