### ISSUE TITLE
`graphql:dump` rake task is only available for Rails apps

### ISSUE THREAD

**Issue by andyw8** [Shopify/shopify-api-ruby#765]
The Rake task is currently loaded as a Railtie:

https://github.com/Shopify/shopify_api/blob/master/lib/shopify_api/graphql/railtie.rb

We should investigate if we can make this available for non-Rails apps (see #764).

**Comment by julioprotzek** [comment]
@catlee I solved this by creating a Rakefile with the following in it:
```ruby
require 'shopify_api'

ShopifyAPI::GraphQL.initialize_clients

load 'shopify_api/graphql/task.rake'
```

Given that you have both `shopify_api` and `rake` in the `Gemfile` for your script you just need to run (for a public app):
```bash
$ bundle exec rake shopify_api:graphql:dump SHOP_DOMAIN="SHOP_NAME.myshopify.com" ACCESS_TOKEN="SHOP_TOKEN" API_VERSION=2020-01
```

Hope this helps! :)
