### ISSUE TITLE
Is it possible not to take any inventory when fulfilling the order using Shopify REST Admin Fulfillment API?

### ISSUE THREAD

**Issue by remy727** [Shopify/shopify-api-ruby#773]
Is it possible **not to take any inventory** when **fulfilling** the order using **Shopify REST Admin Fulfillment API**?

This is the code I used to **fulfill** order.

```
fulfillment = ShopifyAPI::Fulfillment.new(order_id: order_id, location_id: location_id)
fulfillment.notify_customer = false
fulfillment.prefix_options = { order_id: order_id }
fulfillment.save
```

**Comment by andyw8** [comment]
Hi @remy727 

To help understand your needs here, what's the reason for *not* wanting to remove any inventory?
