### ISSUE TITLE
How to filter orders by delivery method?

### ISSUE THREAD

**Issue by vavan19** [Shopify/shopify-api-ruby#780]
I'm trying to filter orders with GraphQL Admin API by query="delivery_method:XXXX" but I can't figure out which field value stands for delivery_method. I've tried almost all fields from Order -> ShippingLine such as carrierIdentifier, title, code, id but it seems like they are not working.
Have some has any idea how it can be done? 
If I'm asking in a wrong place, please redirect me. I'm searching for an answer for quite a while now. Will be glad to see any help.

**Comment by paulomarg** [comment]
Hi @vavan19! Usually, you should send this kind of question to the [Community forums](https://community.shopify.com/) where you'll get faster and more complete answers, GitHub issues are usually used for bug reports.

As per the [Shopify GraphQL reference](https://shopify.dev/docs/admin-api/graphql/reference), you'll find [delivery methods](https://shopify.dev/docs/admin-api/graphql/reference/object/deliverymethod) under fulfillment orders (which themselves are under orders). Perhaps the values you're looking for are in [DeliveryMethodType](https://shopify.dev/docs/admin-api/graphql/reference/object/deliverymethod/deliverymethodtype)?

Hope this helps!
