### ISSUE TITLE
Re-enable variant#inventory_quantity for serialization

### ISSUE THREAD

**Issue by axlekb** [Shopify/shopify-api-ruby#801]
First time venturing into inventory... based on the [docs](https://shopify.dev/docs/admin-api/rest/reference/products/product-variant?api%5Bversion%5D=2020-07)  it appears `variant.inventory_quantity` has re-emerged with a different meaning/use after being deprecated and renamed to `old_inventory_quantity`.  Therefore, I believe it should again be "serialized" with current API versions?

![image](https://user-images.githubusercontent.com/2972314/98892174-c6c88f80-246d-11eb-83c1-030c6c464cb2.png)
https://github.com/Shopify/shopify_api/blob/v9.2.0/test/variant_test.rb

```ruby
 def test_deprecated_inventory_fields_are_included_in_2019_07
    ShopifyAPI::Base.api_version = '2019-07'
    assert @variant.as_json.include?('inventory_quantity')
  end

  def test_deprecated_inventory_fields_are_removed_in_2020_01
    ShopifyAPI::Base.api_version = '2020-01'
    refute @variant.as_json.include?('inventory_quantity')
  end
```

https://github.com/Shopify/shopify_api/blob/v9.2.0/lib/shopify_api/resources/variant.rb
```ruby
def serializable_hash(options = {})
      if allow_inventory_params?
        super(options)
      else
        super(options).tap do |resource|
          (resource['variant'] || resource).except!('inventory_quantity', 'old_inventory_quantity')
        end
      end
    end
```

```ruby
  def allow_inventory_params?
      Base.api_version < ApiVersion.find_version('2019-10')
    end
```

**Comment by paulomarg** [comment]
Hey @axlekb, thank you for reporting this, we'll look into it!
