### ISSUE TITLE
Documentation for hmac Verification?

### ISSUE THREAD

**Issue by asecondwill** [Shopify/shopify-api-ruby#807]
The README states:

> Ensure the provided hmac is valid. The hmac is signed by Shopify, as explained below in the Verification section.

Both hmac and Verification are not mentioned again in the readme.  Is the section missing?

**Comment by paulomarg** [comment]
Hey @asecondwill, that sentence is actually referencing the link to the [OAuth tutorial link](https://shopify.dev/tutorials/authenticate-with-oauth#confirming-installation) which is a bit further down.

That being said, the wording could indeed be improved to better indicate where the Verification details are. We'll tweak that, thank you for reporting this in!

**Comment by ianneub** [comment]
Extra feedback: I was looking for a way to validate Shopify web hooks and stumbled on to this ticket. I also read that section in the README and hoped there would be a Verification section pertaining to my search.
