### ISSUE TITLE
Unclear behavior creating account via Storefront API with First/Last name

### ISSUE THREAD

**Issue by justinholtweb** [Shopify/shopify-api-ruby#823]
We're using Storefront API v2020-04 creating new Shopify customer accounts. We pass email, first and last name but occasionally we see accounts created in Customers showing with just email address and not First and Last name. This is noticeable on a lot of customers created after 11-12-2020, previously it seemed that even when we did not have a first and last name to pass on initial customer creation queries, once we sent the customer address to associate to the checkout this updated that customers record to reflect the First and Last name "magically". To be clear we do NOT run any queries to update the customer profile after creation, but we do associate addresses to checkouts using that customers access token. 

I've dug through release/changelogs and don't see any changes recently that would have caused this odd behavior of first and last name not being associated properly to a customer account. Was there something "behind the scenes" that associated first and last name from address checkout association queries to the customer account previously that was changed or removed?

**Comment by andyw8** [comment]
Hi @justinholtweb

Can confirm if you're using the shopify_api Ruby gem for this?
