### ISSUE TITLE
Shopify Location Delete WebHook Issue

### ISSUE THREAD

**Issue by keshansandeepa** [Shopify/shopify-api-ruby#830]
# Issue summary

Shopify Location Delete WebHook Event View Response Sample Is Wrong .
https://shopify.dev/docs/admin-api/rest/reference/events/webhook?api%5Bversion%5D=2021-01
## Expected behavior

Location Response 

```json
{
  "id": 271878346596884015,
  "sku": "example-sku",
  "created_at": "2021-01-07T17:09:53-05:00",
  "updated_at": "2021-01-07T17:09:53-05:00",
  "requires_shipping": true,
  "cost": null,
  "country_code_of_origin": null,
  "province_code_of_origin": null,
  "harmonized_system_code": null,
  "tracked": true,
  "country_harmonized_system_codes": [
  ],
  "admin_graphql_api_id": "gid:\/\/shopify\/InventoryItem\/271878346596884015"
}
```
## Actual behavior

Its Only Send the Location ID 

```json
{
   "id" : 58994327711
}
```

## Steps to reproduce the problem
Create and Delete the Shopify Location 

## Specifications

- `shopify_api` version: 2021-01

**Comment by paulomarg** [comment]
Thank you for reporting this, I'll forward it internally so we can fix it.

**Comment by paulomarg** [comment]
Thanks for reporting this @keshansandeepa, we'll investigate it.

**Comment by ashleyww93** [comment]
I can confirm this is still happening.
