### ISSUE TITLE
POST Theme - 20 MB limit

### ISSUE THREAD

**Issue by guillelopezgines** [Shopify/shopify-api-ruby#838]
# Issue summary

When using the endpoint: `POST /admin/api/2020-10/themes.json` the max file size for the zip file specified at the `src` parameter is currently 20MB, when through Shopify's backoffice at `/admin/pages` is 50MB.

## Expected behavior

I expect the zip size limit on the API to be the same as in the admin: 50MB. Or even higher.

## Actual behavior

Currently it's limited to 20MB. Getting an error if it's above this limit.

## Specifications

- Shopify API version used: `2020-10`

**Comment by tanema** [comment]
Can you tell me what error your are getting because the contents of our theme model is
```ruby
module ShopifyAPI
  class Theme < Base
  end
end
```
There is no validation on our side whatsoever.

**Comment by guillelopezgines** [comment]
The error we get says:

```
"Src may not be used to fetch a file bigger than 50MB"
```

**Comment by andyw8** [comment]
(this came up previously in https://github.com/Shopify/shopify_api/issues/395 )
