### ISSUE TITLE
Error Fetching Usage Charges

### ISSUE THREAD

**Issue by asecondwill** [Shopify/shopify-api-ruby#839]
# Issue summary

Write a short description of the issue here ↓

I'm trying to get a list of all the charges made for my Shopify App.  I have created a ShopifyAPI::RecurringApplicationCharge, stored the id and then look for the charges as per this line

https://github.com/Shopify/shopify_api/blob/49ac8ccd0235233bd5ff2b67c0204636d5dcbb01/lib/shopify_api/resources/recurring_application_charge.rb#L16
`
@charges = ShopifyAPI::UsageCharge.find(:all, params: { recurring_application_charge_id: 20801454252 })`

## Expected behavior

I should get a collection of charges?

## Actual behavior

I get an error:
```
ActiveResource::MissingPrefixParam in Retailer::ShopifyController#charges
recurring_application_charge_id prefix_option is missing
```

## Specifications

- `shopify_api` version:9.3.0
- `activeresource` version:5.1.1
- Shopify API version used (example: `2020-10`):

**Comment by paulomarg** [comment]
Thanks for reporting this @asecondwill, we'll investigate it!

**Comment by mllemango** [comment]
Hey @asecondwill, do you see the same error if you try to get the usage charge with the following?
```
rec_charge = ShopifyAPI::RecurringApplicationCharge.find(21194801315)
@charge = rec_charge.usage_charges
```
Could you attach logs if that's the case?

**Comment by asecondwill** [comment]
Hi, sorry for the delay on this.  got put on something else. 

Trying your suggestion:```

rec_charge = ShopifyAPI::RecurringApplicationCharge.find(@current_retailer.shopify_charge_id )

#<ShopifyAPI::RecurringApplicationCharge:0x00007fa6456ab6f0 @attributes={"id"=>22064857260, "name"=>"Basic Plan", "api_client_id"=>4447377, "price"=>"29.00", "status"=>"accepted", "return_url"=>"https://e0c25fbbf27a.ngrok.io/retailer/shopify/charges", "billing_on"=>nil, "created_at"=>"2021-04-08T09:53:06-04:00", "updated_at"=>"2021-04-08T09:53:53-04:00", "test"=>true, "activated_on"=>nil, "cancelled_on"=>nil, "trial_days"=>0, "trial_ends_on"=>nil, "decorated_return_url"=>"https://e0c25fbbf27a.ngrok.io/retailer/shopify/charges?charge_id=22064857260"}, @prefix_options={}, @persisted=true>
```
And then

```
@charge = rec_charge.usage_charges
*** ActiveResource::ForbiddenAccess Exception: Failed.  Response code = 403.  Response message = Forbidden (Forbidden).
```
