### ISSUE TITLE
Is it clear which API this gem is for? (Admin vs Storefront vs Partner)

### ISSUE THREAD

**Issue by dechimp** [Shopify/shopify-api-ruby#840]
I feel like Shopify's Storefront and Partner API's should be addressed in the Readme. I see issues and forum posts where developers are having trouble accessing the Storefront API, which I dont believe this gem supports (or am I wrong?).   If they are not supported, the readme should probably say so.  It took me a while before I noticed that this gem is aimed at the Admin API.  

I would be happy to contribute a PR if I can confirm which API's this gem supports.  Thanks.

**Comment by paulomarg** [comment]
Hi @dechimp, thank you for bringing this up. This gem only implements access to the Admin API, as currently stated in the README:
```
The Shopify API gem allows Ruby developers to access the admin section of Shopify stores programmatically.
```

Perhaps we could improve the wording here to explicitly mention the Admin API to make it easier to spot which API the gem is meant for.
