### ISSUE TITLE
Documentation for setting headers on requests for e.g. presentment prices?

### ISSUE THREAD

**Issue by bentona** [Shopify/shopify-api-ruby#857]
# Issue summary

Missing documentation regarding setting headers

## Expected behavior

According to API docs, we should include a special header to receive presentment price information in Product responses (https://shopify.dev/tutorials/migrate-your-app-to-support-multi-currency). It isn't clear how this is possible with the gem's API.

Happy to tackle this if someone can point me in the right direction.

**Comment by mllemango** [comment]
Hey @bentona, thanks for bringing this up. It doesn't seem like the library supports presentment prices at the moment. Headers are a bit hard to work with, as outlined in #501. You can edit your local files to add a custom header by doing the following:
```
class Product < ShopifyAPI::Product
  def self.headers
    super.merge('X-Shopify-Api-Features' => 'include-presentment-prices')
  end
end

product = Product.find(product_id)
```
