### ISSUE TITLE
Is there any plan to release schema API calls for Admin API?

### ISSUE THREAD

**Issue by svatada** [Shopify/shopify-api-ruby#860]
# Issue summary
Need API calls to fetch schema object for Admin API resources (orders, products, customers..etc)

We are from leading Data integration platform. We build components for applications (Workday, Netsuite, SAP....etc) and add them to our Tool.  Using these prebuilt components, we design integrations by interconnecting them each other by providing field mappings to source and target component to achieve customers business needs.  To make users job easy, we populate schema information in our components but for Shopify component we are unable to achieve schema population dynamically as there is no support available. 

Shopify releasing version updates for every quarter and deprecating resource properties some times. In such scenarios developer need to update their application with updated resource properties. If Shopify has API calls to get schema, then developers job would become easy to read resource schema specific to version without modifying their code.

Having schema API call from Shopify would make developers job easy. Hope Shopify will think about it in future release.  

## Specifications

- `shopify_api` version: 2021-04
- `activeresource` version: 2021-04
- Shopify API version used (example: `2020-07`): 2021-04

**Comment by mkevinosullivan** [comment]
Hi @svatada, thanks for submitting your request.  Presently we have no plans for a schema API but will add it to the backlog for consideration.

**Comment by svatada** [comment]
Thanks @mkevinosullivan

**Comment by nelsonwittwer** [comment]
Would love to add this at some point but it is still not on our immediate road map.
