### ISSUE TITLE
warning: URI.escape is obsolete

### ISSUE THREAD

**Issue by techvineet** [Shopify/shopify-api-ruby#864]
# Issue summary

Write a short description of the issue here ↓

Getting a warning `shopify_api-9.4.1/lib/shopify_api/session.rb:191: warning: URI.escape is obsolete`

## Expected behavior

What do you think should happen?
Should not receive this warning.

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

Getting a warning `shopify_api-9.4.1/lib/shopify_api/session.rb:191: warning: URI.escape is obsolete`

## Steps to reproduce the problem

1.
1.
1.

## Logs
If applicable, enable the logs as described in the README, and paste the relevant portion here.
NA

## Specifications

- `Ruby Version`: 2.7.2
- `Rails Version`: 6.1.3.2
- `shopify_api` version: 9.7.1
- `activeresource` version: 5.1.1
- Shopify API version used (example: `2020-07`):

**Comment by andyw8** [comment]
@techvineet thanks for the report, this is due to a change in Ruby 2.7. We'll try to eliminate the warning.
