### ISSUE TITLE
Use ShopifyAPI::Session with private apps

### ISSUE THREAD

**Issue by key88sf** [Shopify/shopify-api-ruby#880]
# Issue summary

Is there any way to use `ShopifyAPI::Session` with a **private** app's credentials? We have an application that needs to connection to multiple shopify stores, and each store has a private app for accessing API data. We don't want to constantly be changing `ShopifyAPI::Base.site`, etc, since it seems like this is not safe if multiple threads are accessing the API at the same time for different stores.

## Expected behavior

What do you think should happen?
* Be able to open a temporarily `ShopifyAPI::Session` using the APIKey and Password from a private app.

## Specifications

- `shopify_api` version: 9.4.1
- `activeresource` version: 6.1.x
- Shopify API version used (example: `2020-07`):  2021-07

**Comment by mrpunkin** [comment]
The following seems to work fine for me to access a session for a shop that isn't my base shop settings. Obviously replace the domain and token with actual values for the shop's domain and the private app password.

```
sess = ShopifyAPI::Session.new(domain: 'site.myshopify.com', token: 'private-app-password', api_version: '2022-01')
ShopifyAPI::Base.activate_session(sess)
```

**Comment by josegrad** [comment]
We use exactly that. Our problem is that if connect to the API for a different shop, that uses no token (old private apps) the the token stays in the session, and authentication fails.

Thought I´m not sure what you mean by "for a shop that isn't my base shop settings.

Our systems handles many shops. So we don´t have a shop of our own.

**Comment by mrpunkin** [comment]
I simply just meant whatever settings ShopifyAPI::Base was retaining as opposed to a specific session object. My wording was based on writing internal apps for only a single shop, sorry.

I'm not quite sure what you mean by old private apps though. All private apps I've ever used had credentials, are you saying there was a period when they didn't?
