### ISSUE TITLE
How do I access version 9 credentials with the new custom App screen on shopify?

### ISSUE THREAD

**Issue by achadee** [Shopify/shopify-api-ruby#915]
# Issue summary

We are not ready to update to version 10 as it looks like a lot has changed. How do I create a private app to onboard a new developer on the team so I can do the following:

```
shop_url = "https://#{ENV["SHOPIFY_API_KEY"]}:#{ENV["SHOPIFY_API_PASSWORD"]}@#{ENV["SHOPIFY_SHOP_NAME"]}.myshopify.com"
ShopifyAPI::Base.site = shop_url
ShopifyAPI::Base.api_version = "2020-04"
```

Currently on version 9

This is what I see:
![Screen Shot 2022-04-05 at 3 00 15 pm](https://user-images.githubusercontent.com/5952918/161682204-ba873328-3a54-4c0b-a08b-c55db9cc707d.png)

But the credentials dont work for the `shop_url` method

thanks!

**Comment by resistorsoftware** [comment]
Still using 2020-4?
