### ISSUE TITLE
How do I get `option1`, `option2`, `option3` using `ShopifyAPI::Product` (or `ShopifyAPI::Variant`) ?

### ISSUE THREAD

**Issue by koshigoe** [Shopify/shopify-api-ruby#918]
# Issue summary

Product Variant have option1, option2, option3.

- https://shopify.dev/api/admin-rest/2022-01/resources/product#get-products

```json
{
  "products": [
    {
      "variants": [
        {
          ...
          "option1": "Pink",
          "option2": null,
          "option3": null,
          ...
        },
      ],
      ...
    },
    ...
  ]
}
```

But `ShopifyAPI::Variant` does not take these values from API response.
(The `ShopifyAPI::Variant` does not have accessor `option1`, `option2`, `option3`.)

```ruby
products = ShopifyAPI::Product.all
products.first.variants.first.option1 # NoMethodError
```

## Expected behavior

I'd like to get `option1`, `option2`, `option3` using `ShopifyAPI::Variant`.

```ruby
products = ShopifyAPI::Product.all
products.first.variants.first.option1 # => "Pink"
```

## Actual behavior

The `ShopifyAPI::Variant` does not have accessors `option1`, `option2`, `option3`.

```ruby
products = ShopifyAPI::Product.all
products.first.variants.first.option1 # NoMethodError
```

So, I think `ShopifyAPI::Rest::Base.create_instance` reject `option1`, `option2`, `option3` from API response.

https://github.com/Shopify/shopify_api/blob/4fdb0fca796cc6d3960d39733f4cbde89d572ce2/lib/shopify_api/rest/base.rb#L208-L234

```
> ShopifyAPI::Variant.instance_methods(false).select { |method| !method.to_s.include?("=") }
=> [:barcode,
 :compare_at_price,
 :fulfillment_service,
 :image_id,
 :inventory_item_id,
 :id,
 :inventory_management,
 :inventory_quantity,
 :inventory_policy,
 :updated_at,
 :price,
 :requires_shipping,
 :sku,
 :taxable,
 :weight_unit,
 :weight,
 :inventory_quantity_adjustment,
 :old_inventory_quantity,
 :presentment_prices,
 :tax_code,
 :title,
 :grams,
 :option,
 :position,
 :created_at,
 :product_id]
```

## Steps to reproduce the problem

1. Get Product Variant using `ShopifyAPI::Product` or `ShopifyAPI::Variant`
1. Try to get `option1`

## Specifications

- `shopify_api` version: 10.0.0
- Shopify API version used `2022-01`

**Comment by paulomarg** [comment]
Thanks @koshigoe, I think you're spot on here, and we're ignoring those dynamic fields when we set up the object. We'll make sure we're setting anything we get back from Shopify to the objects and that you can access them afterwards.
