### ISSUE TITLE
Unable to create Orders in latest version

### ISSUE THREAD

**Issue by aashishpsaini** [Shopify/shopify-api-ruby#972]
# Issue summary

In version 9, we can create orders using `ShopifyAPI::Order.create`, however for versions >9.5 I couldn't find that under in console.

## Expected behavior

Should be able to create Order using gem

## Actual behavior

Unable to create Order rather find it 

## Logs
If applicable, enable the logs as described in the README, and paste the relevant portion here.
```
ShopifyAPI::Order.new
NameError: uninitialized constant ShopifyAPI::Order
from (pry):32:in `<main>'
```

## Specifications

- `shopify_api` version: 10.0

**Comment by awd** [comment]
A couple of things to try here...

Is `NameError: uninitialized constant ShopifyAPI::Order` showing up in your test environment or in dev/prod? 

Double check that `ShopifyAPI::Context.setup?` is `true` in dev/test/prod environments. You may need to add ENV vars to those environments (and CI of course).

If it's false, check that the required keys are available to those environments:
`ShopifyApp.configuration.api_key`
`ShopifyApp.configuration.secret`

If the context setup fails, the `ShopifyAPI::Order` will raise the error you've mentioned.

Lastly, you would want to do something like this instead:
```ruby
order = ShopifyAPI::Order.new
order.something = something
order.save
```

**Comment by artyrcheek** [comment]
Im seeing this issue also, but even with ShopifyAPI::Context.setup? returning true

**Comment by artyrcheek** [comment]
Okay, it looks like its because my api_version is set to `unstable`
