### ISSUE TITLE
Why Shopify is not actively taking more care of these issues?

### ISSUE THREAD

**Issue by guillelopezgines** [Shopify/shopify-api-ruby#986]
For the last 6 months I have created 5 issues and till today, none of them have been fixed (https://github.com/Shopify/shopify-api-ruby/issues/created_by/guillelopezgines).

As Shopify Partners, we heavily rely on Shopify's API working properly. And it's a pity that if we report an issue, we don't see any urgency from Shopify on fixing those. We think Shopify could do better here, and lacking other channels where to communicate this, we decided to write it here. We hope actions can be taken to revert this situation. Thanks.

**Comment by Fladdermuz** [comment]
@guillelopezgines it's infuriating to be forced to use the new version, as the ability to add the older API keys hase been removed from stores. So now they force those of us who are doing private apps to upgrade to a total TERD.

**Comment by benichu** [comment]
@Fladdermuz infuriating indeed :angry: 

Re: https://github.com/Shopify/shopify-api-ruby/issues/969#issuecomment-1351216606

**Comment by acflint** [comment]
still not stale :)

**Comment by acflint** [comment]
This continues to not be stale :)

**Comment by nelsonwittwer** [comment]
We are working on cleaning things up! You aren't alone with your feedback and we've heard you. [Here is our plan to improve the ruby ecosystem](https://github.com/Shopify/shopify-api-ruby/issues/1181#issuecomment-1675925678) in case you missed that discussion. I'm closing this issue so we can have a single thread on this subject. If you have concerns with our plan, let's move the discussion to that issue I've linked above. Thank you again for your patience!
